### ISSUE TITLE
Map Data Convert

### ISSUE THREAD

**Issue by Pantyhose-X** [mircokroon/minecraft-world-downloader#100]
Hello @mircokroon 

- We need an Minecraft Map Convert tool

- I convert Minecraft map data to Minetest map data ?

[Minetest](https://www.minetest.net/)
![Minetest](https://user-images.githubusercontent.com/42504385/106380630-0a4ced00-6410-11eb-8540-a06675e9f4a8.JPG)

**Comment by mircokroon** [comment]
Hey, what do you mean exactly?

**Comment by Survivalwar** [comment]
> Hey, what do you mean exactly?

@mircokroon Map Convert tool

**Comment by Pantyhose-X** [comment]
> Hey, what do you mean exactly?

Convert Minecraft maps to Minetest worlds Function ? 

[L map](https://www.planetminecraft.com/project/novigrad-timelapse-download/)

Reference
https://forum.minetest.net/viewtopic.php?f=12&t=13709&sid=64ab4a65e2791ce2b615a536130c7014

https://forum.minetest.net/viewtopic.php?f=14&t=14271&sid=3cd2c3fc6dedd9d79bdc4bf396b1b7d9
