### ISSUE TITLE
Unable to access jarfile world-downloader.jar

### ISSUE THREAD

**Issue by ChineseT** [mircokroon/minecraft-world-downloader#104]
I have the correct java version, etc, I get an error that says "Unable to access jarfile world-downloader.jar"

The file is in my \downloads folder at the moment.

**Comment by mircokroon** [comment]
Make sure your commandline is also set to the correct directory, e.g. by typing ```cd C:/users/.../downloads/``` or by opening the commandline from the directory it's in by going to File -> Open in powershell/cmd.
