### ISSUE TITLE
Failed to connect to server 1.15.2 linux

### ISSUE THREAD

**Issue by ChillerDragon** [mircokroon/minecraft-world-downloader#11]
OS: debian10
Minecraft client: https://github.com/kz6fittycent/mc-installer
Minecraft version: 1.15.2 (server and client are vanilla)

```
$ java -jar world-downloader.jar --server=zillyhuhn.com --minecraft=/home/$USER/snap/mc-installer/current/.minecraft
Starting proxy for zillyhuhn.com. Make sure to connect to localhost:25565 instead of the regular server address.
Performed handshake with zillyhuhn.com:25565, protocol version 578 :: next state: login
Login by: ZillyHuhn
Client probably disconnected. Waiting for new connection...
WARNING: packet parsing may have been incorrect! Expected length: 261. Used bytes: 0
Server probably disconnected. Waiting for new connection...
```

**Comment by ChillerDragon** [comment]
Okay @mircokroon now that I am able to build the thing (:tada:) I could help.

Do you want some debug messages somewhere? Should I try different versions? Or can you reproduce the issue?

**Comment by mircokroon** [comment]
I was able to reproduce it using the Linux subsystem for Windows but I don't quite see what's causing it yet, I'll see if I can do some more investigating today

**Comment by mircokroon** [comment]
@ChillerDragon I believe it should work now on the [linux-auth](/mircokroon/minecraft-world-downloader/tree/linux-auth) branch. If it works for you I'll merge it.

The issue was that it would try to read from %appdata% even on Linux systems (and when %appdata% wasn't even in the given Minecraft path). The exception that would have been printed due to this was swallowed silently.

**Comment by ChillerDragon** [comment]
@mircokroon great it works! The error message is helpful and providing the ``--minecraft=/home/$USER/snap/mc-installer/current/.minecraft`` argument worked for me. Maybe you can use ``~/.minecraft`` as default on linux instead of ``%appdata%``.

**Comment by mircokroon** [comment]
Good idea, I changed the default as well.
