### ISSUE TITLE
It just starts to proxy and when i connect to local it wites that i logged in and then it does... nothing

### ISSUE THREAD

**Issue by fym35** [mircokroon/minecraft-world-downloader#111]
**Describe the bug**
It just starts to proxy and when i connect to local it wites that i logged in and then it does... nothing

**Steps to reproduce**
i just normally started it

**Log output**
```
Starting proxy for ms60.hicoria.cloud:58770. Make sure to connect to localhost:25565 instead of the regular server address.
Performed handshake with ms60.hicoria.cloud:58770, protocol version 754 :: next state: login
Login by: KONG_CZ1
Enabled compression
Login success: KONG_CZ1 logged in with uuid 8b8076857b15393dae8b558bc12a909c
Using protocol of game version 1.16.2 (754)

```
**Screenshots**
![x](https://user-images.githubusercontent.com/57803365/107919269-539e5000-6f6b-11eb-94ea-66e96638f662.PNG)

**Version**
 - Game: Minecraft 1.16.5
 - Downloader: latest
 - Launcher (if login issues): 14.2

**Comment by mircokroon** [comment]
Uh, are you sure it's doing nothing? If you run it without the GUI it's pretty quiet and could just be saving the world. It doesn't really print anything unless something goes wrong.
