### ISSUE TITLE
Starting the .exe with command line parameters leaves a zombie process behind when the main window is closed.

### ISSUE THREAD

**Issue by leandrotlz** [mircokroon/minecraft-world-downloader#116]
**Describe the bug**
When running `world-downloader.exe -s <server>` from a shortcut or the command line, the settings window is skipped and the main preview window is opened directly, which is expected. However, closing that window **does not** end the program; javaw.exe will continue running in the background, accepting proxy connections with no visible indication that world-downloader is running.

This was already the case with the .jar version, but with the .jar version you had a separate console window that you could close to terminate the java process. The .exe version has no console, and thus no way to terminate the process other than Task Manager.

**Steps to reproduce**
Start world-downloader from the command line using any given parameters. Just providing a server is enough. Then, close the main window using the X icon in the title bar. Refreshing the server list in Minecraft will show that it is still running and accepting connections; the javaw.exe process for world-downloader will still be in the Task Manager.

**Version**
 - Downloader: v1.11.3

**Comment by mircokroon** [comment]
Thanks, fixed it by just always exiting when the GUI is closed. I don't think it was a very valuable feature to leave it running when launched through the terminal anyway.
