### ISSUE TITLE
Does not save chest or shulker box inventories

### ISSUE THREAD

**Issue by edelsone** [mircokroon/minecraft-world-downloader#124]
**Describe the bug**
The documentation says that if I open a chest, the chest content will be saved. This does not happen.

**Steps to reproduce**
Launch program, enter world address, provide world save location.
Using vanilla client (1.16.5), connect.
Upon connection, I see that the map begins to draw, so I know that I'm connecting through the tool, and not direct to the server.
Open a shulker box filled with valuables. Close it.
Open a barrel filled with valuables. Close it.
Open a double-chest filled with valuables. Close it.
Exit game.
Right-click in downloader, select "Save & Exit".
Restart game, go into singleplayer world.
Receive version mismatch warning, click "Create Backup and Load" button.
Shulker box is empty.
Barrel is empty.
Double chest is empty.

**Log output**
```

...

```
**Screenshots**

**Version**
 - Game: Minecraft 1.16.5
 - Downloader: latest
 - Launcher (if login issues): latest

**Comment by mircokroon** [comment]
Thanks for the report! Unfortunately I can't reproduce this currently, all three of these seem to get saved correctly for me. There are two cases I can think of that might cause this.
1. If the blocks were placed after the chunk was already loaded, currently no tile entities will be saved for that block
2. If the server is non-vanilla and sends chest tile entities for shulkers and barrels, you could probably verify this by seeing if a regular single-chest works

Do either of these apply to your scenario?

**Comment by edelsone** [comment]
I tried again, and _almost_ every time, all I'm getting are empty containers. During _one_ of my tests, a named shulker box was saved with its content, but I couldn't reproduce that. Named or unnamed shulker, named or unnamed barrel, single chest, double chest, the tile entity data (including the container name where relevant) isn't being saved.

**Comment by mircokroon** [comment]
Ah I think I've found the problem, there is an issue with parsing coordinates of inventories where it's correct in certain coordinate ranges but not in others. I'll release a fix in a couple hours.

**Comment by mircokroon** [comment]
Should be fixed now, let me know if you're still experiencing problems

**Comment by edelsone** [comment]
Yes, it works very nicely now. Still doesn't save the player's inventory, but I don't know whether it's supposed to or not.
