### ISSUE TITLE
Lighting issues with downloaded chunks.

### ISSUE THREAD

**Issue by Esper89** [mircokroon/minecraft-world-downloader#128]
**Describe the bug**
When viewing chunks that have been previously downloaded (via the render distance extending feature), the lighting will be somewhat off. In vanilla, the only thing I've noticed is that underwater blocks appear brighter than they should. When using the [Phosphor](https://github.com/CaffeineMC/phosphor-fabric) lighting optimization mod, these chunks appear completely dark.

**Steps to reproduce**
1. Use the world downloader on a server with a render distance less than your client's, and use the `--extend-render-distance` option to tell it your client's render distance.
2. Load in enough of the server that some of it won't be within the server's render distance of you when you next log in. Make sure to load in some chunks with ocean in them.
3. Exit the server, shut down the downloader, then start it back up (with the same arguments) and log back into the server.
4. Observe the ocean. The chunks that are within the server's render distance will appear to have darker water than the chunks that are within the client's* render distance but not the server's.
5. Exit the server, shut down the downloader, install the [Phosphor](https://github.com/CaffeineMC/phosphor-fabric) mod, then start the downloader again with the same arguments and log back in to the server.
6. Observe how all chunks within the client's render distance but not the server's appear significantly darker than chunks within the server's render distance. In fact, they appear to have no light at all.

**Log output**
The console did not output any errors, so I included my minecraft client logs. My logs appear to be filled to the brim with errors, regardless of if the downloader was in use or not. It looks like it's an error with the fabric loader and the server I tested on. To help in telling these errors apart from actual ones, I have included logs from when the downloader was not in use. 

[Downloader in use, no mods installed.](https://github.com/mircokroon/minecraft-world-downloader/files/6098610/no_mods%2Bdownloader.log)
[Downloader in use, phosphor installed.](https://github.com/mircokroon/minecraft-world-downloader/files/6098614/phosphor%2Bdownloader.log)
[Downloader not in use, no mods installed.](https://github.com/mircokroon/minecraft-world-downloader/files/6098616/no_mods%2Bno_downloader.log)
[Downloader not in use, phosphor installed.](https://github.com/mircokroon/minecraft-world-downloader/files/6098618/phosphor%2Bno_downloader.log)

**Screenshots**

With no mods:
![no_mods_water](https://user-images.githubusercontent.com/69338029/110268340-7e3e6000-7f8f-11eb-844a-93a7625294a7.png)
![no_mods_land](https://user-images.githubusercontent.com/69338029/110268385-8dbda900-7f8f-11eb-8c6c-a965a3319392.png)

With Phosphor:
![phosphor_water](https://user-images.githubusercontent.com/69338029/110268403-9615e400-7f8f-11eb-98a3-82dcf154aa08.png)
![phosphor_land](https://user-images.githubusercontent.com/69338029/110268410-97dfa780-7f8f-11eb-9827-3d06b99d47ac.png)

**Version**
 - Game: Minecraft Fabric 1.16.5
 - Downloader: latest (1.13.1)
 - Launcher: 2.2.1867

**Notes**
 - "No mods" does not count the fabric loader, which was installed for all these tests.
 - The fabric API was not installed for any of these tests.
 - There were no error messages of any kind in the console output of the downloader.
 - In case the world file in question is useful in debugging this, [here](https://github.com/mircokroon/minecraft-world-downloader/files/6098645/world.zip) it is.
 - This is a newly created world using the latest version of the downloader, though the issue is also present when using worlds created by older versions.

**Comment by mircokroon** [comment]
I guess this is because currently no lighting information is sent for the extended chunks, in vanilla it seems pretty unnoticeable usually so I guess the client does generate them manually or something. I'll see if I can send some lighting packets as well for 1.16+ to fix this issue.

**Comment by Esper89** [comment]
If the client generates lighting information manually then that would explain the massive lag spikes on first loading in to the server, when there are many saved chunks around you. The first few frames can take my computer over a minute if there's already a lot of saved chunks near me, and if I'm not using phosphor.

**Comment by Esper89** [comment]
It's definitely working better than before. As you noticed, there are still some dark chunks; it seems like servers with lower render distances may have more of them. This server has a measured render distance of 6 chunks:
![dark_chunks](https://user-images.githubusercontent.com/69338029/110523333-f451dc80-80df-11eb-9cfd-bc057e79cec7.png)
I also noticed a few "missing" chunks, as you can see in the screenshot - they weren't actually missing, and some of them would load in when I got closer to them or looked directly at them for long enough. There was nothing in stderr and no errors in stdout, unfortunately.

Since the lag without Phosphor is fixed, I think I'll refrain from using it with the downloader, for the time being.

**Comment by mircokroon** [comment]
The holes turned out to be the last chunk in each region, which were being skipped due to a `>=` instead of `>`, so that was easily fixed.

Still looking into the black spots to see if they can be fixed. It seems to happen when a chunk is loaded for a second time, then the downloader assigns the lighting to the old chunk before replacing it with the new one. I'll see if it can be fixed tomorrow.

**Comment by mircokroon** [comment]
Fixed that as well! Let me know if you encounter any other issues.
