### ISSUE TITLE
Scrolling and moving around makes world very small

### ISSUE THREAD

**Issue by maxsupermanhd** [mircokroon/minecraft-world-downloader#137]
Can not zoom in at all, it is jammed between 100 and 200. Also after done dragging map it restores zoom to maximum possible when must stay on level of player track.

This is maximum zoom in I can get: 
![pic](https://user-images.githubusercontent.com/20772987/111561383-68a61300-87a5-11eb-95f4-290b2dc37e3e.png)

**Comment by mircokroon** [comment]
Hmm strange, since I can't reproduce this myself, could you add a quick debug print and see what's going on when you scroll? Line 382 of `gui.GuiMap.java` should do the trick:

```java
    private void bindScroll() {
        entityCanvas.setOnScroll(scrollEvent -> {

            System.out.println("Scrolled: " + scrollEvent.getDeltaY());

            int zoom = Config.getZoomLevel();
            if (scrollEvent.getDeltaY() > 0) {
        ...
```

**Comment by maxsupermanhd** [comment]
Yes, I did exact same thing when encountered this issue :grin:, it reports 100 and 200 and what more interesting when scrolling one way it is only 200 but when in other direction it is 100 and then 200 back.

**Comment by mircokroon** [comment]
Unfortunately I have no idea how to fix this. I changed the zoom handler to work on the pane instead of the canvas, in case the canvas somehow causes problems on some platforms. I also added +/- to scroll as well so that you can still make use of it even if you can't scroll for this or any other reason.
