### ISSUE TITLE
Feature Request: Nether Roof

### ISSUE THREAD

**Issue by Gaming32** [mircokroon/minecraft-world-downloader#138]
My request is that the minimap shows what's on the nether roof when the player is above Y=128 in the nether.

**Comment by gaming32** [comment]
Hmmm...
This seems more complicated than I thought at first. It seems as though the `ChunkImageFactory` never has access to the player's Y position, or any position at all for that matter.

**Comment by mircokroon** [comment]
Well it can get it through `WorldManager.getInstance().getPlayerPosition()` or something. The main complication here is that only newly loaded chunks would be rendered as such, so if the player enters the nether ceiling the chunks they are currently in will still be rendered as they are now. I guess the player could always manually redraw the chunks through the context menu so maybe its fine.

**Comment by Gaming32** [comment]
That seems good! (It's better than nothing imo) Also with #149, that could lead to some automatic reloading.
