### ISSUE TITLE
[Feature Request] Download block inventory (chest etc)

### ISSUE THREAD

**Issue by SakuraKoi** [mircokroon/minecraft-world-downloader#14]
Save chest's inventory while player is opening a chest(so the inventory is sent to client)

Thank you for making this awesome tool!

**Comment by mircokroon** [comment]
This is definitely something I'd like to see as well, main issue currently is that I'm not sure how to connect the inventory data to the correct chest.

**Comment by SakuraKoi** [comment]
Maybe it could be done by record what chest is interacted last, and if the inventory is sent to the client, link the inventory with the last clicked chest?
I guess it may cause a bug if the server is very lag, eg: A player clicked chest, but no response sent from the server, and he clicked another one, and the before one opened

But at least it works XD

**Comment by mircokroon** [comment]
That sounds like a good idea, however then the next issue is that I'm not sure which [packet](https://wiki.vg/Protocol#Serverbound_4) actually relates to the client wanting to open a chest. It's possible that it will need some form of raytracing as well. Some more research is needed.

**Comment by SakuraKoi** [comment]
It looks like using the [Block Placement](https://wiki.vg/Protocol#Player_Block_Placement) packet.
Some code can be found at net.minecraft.network.NetHandlerPlayServer and net.minecraft.server.management.ItemInWorldManager.activateBlockOrUseItem()

**Comment by mircokroon** [comment]
Seems to be how it works indeed. I guess 'block placement' is a bit poorly named.

Thank you for your efforts! I'll look into implementing it soon.
