### ISSUE TITLE
Can't download a world for a modded server

### ISSUE THREAD

**Issue by SolidBlock-cn** [mircokroon/minecraft-world-downloader#157]
It's a 1.12.2 server with many forge mods. It does NOT require your mojang authentification and requires a lot of mods. When I start downloading, no chunks fetched. So how to download this kind of server world?
Besides, does it require a Minecraft instance running when using this wdl?

**Comment by mircokroon** [comment]
Yes, the downloader works by connecting to it through Minecraft. On it's own it does nothing.
