### ISSUE TITLE
Seed function does not work

### ISSUE THREAD

**Issue by flurfsted** [mircokroon/minecraft-world-downloader#168]
When i use the seed function, save the world, the seed does not save. It is in my config file

**Comment by mircokroon** [comment]
Do you mean that when you type `/seed` in-game, it is not the same as what you set in the downloader?

**Comment by flurfsted** [comment]
yes exactly

**Comment by udese** [comment]
Adding to this, looking in level.dat right after downloading, the seed is the same but it then changes after loading in the world.

**Comment by flurfsted** [comment]
any fix?

**Comment by mircokroon** [comment]
There's been some changes to how the seed/world generator settings are stored, I should be able to fix it but it may take a day or two.

As a workaround you could probably generate a world world with the desired seed manually and then copy the `level.dat` into the downloaded world's folder.
