### ISSUE TITLE
World Saves No Longer Load in Chunky

### ISSUE THREAD

**Issue by 2fncool** [mircokroon/minecraft-world-downloader#184]
World saves created by world downloader 1.14.x no longer load in Chunky, a rendering program available at https://chunky.llbit.se/.  Chunky could load worlds saved by world-downloader 1.8.3.  I can no longer test older versions due to the recent change in authentication so I cannot determine the version where saves stopped loading.  Chunky has been on version 2.3.0 since I began using it so the change is with the world saves.  If the issue is with Chunky, I'm happy to open an issue at https://github.com/chunky-dev/chunky/issues .

To reproduce the problem, open a world save from world-downloader.exe/jar in Chunky.  Getting Chunky to run for the first time can be a pain and varies from system to system.  I'm happy to test any world saves with my instance of Chunky.  Chunky will show a question mark for all chunks.  Hovering over any chunk will show each chunk as "unknown".

Chunky WILL load world saves from world-downloader if they are first opened within Minecraft and every chunk is explored which is very time consuming for large world saves.

I appreciate any effort on this since I mainly use world-downloader to create renders of large areas (ie. 2k x 2k blocks).  Thank you.

minecraft-world-downloader 1.14.3 world opened in Chunky 2.3.0:
![Chunky error 3](https://user-images.githubusercontent.com/87552213/126845231-19543628-0080-4794-bf5e-8eb09501226d.jpg)

The world save used above:
[Chunky_test.zip](https://github.com/mircokroon/minecraft-world-downloader/files/6871392/Chunky_test.zip)

Same world in Chunky after being opened in vanilla Minecraft:
![Chunk working 2](https://user-images.githubusercontent.com/87552213/126845328-35bd8b7b-6eb6-43b3-91f2-f3c520627188.jpg)

**Comment by mircokroon** [comment]
Well I guess it's an issue with Chunky in some way since it's not able to understand a world file that Minecraft does understand. I'll look into it tomorrow to see if it's something that I can fix easily.

**Comment by 2fncool** [comment]
I appreciate it.  I was mainly wondering if you changed something with the way worlds are saved.

**Comment by mircokroon** [comment]
This seems to be an issue thats already fixed in Chunky, they just haven't released a version with the fixed code in it yet. If possible you could try building Chunky yourself and it should work fine.

**Comment by 2fncool** [comment]
Fantastic news!  Thank you for the information and your time.  I will try to build Chunky.  This should save me a ton of time.
