### ISSUE TITLE
Way to offset already downloaded chunks

### ISSUE THREAD

**Issue by maxsupermanhd** [mircokroon/minecraft-world-downloader#188]
So basically I downloaded whole thing and forgot to set offsets, how can I fix it? I want to move all chunks closer to 0 0, including nether dimension. Is there a way to do so?

**Comment by mircokroon** [comment]
Not using this application currently, I guess if you don't mind moving by increments of 512 blocks you can write a script to rename the region files

**Comment by maxsupermanhd** [comment]
Wait, will just renaming region files move whole thing?

**Comment by mircokroon** [comment]
Mostly, it'll break entities and tile entities unfortunately, but depending on your use case maybe thats not an issue. For just moving blocks, you can rename them, e.g. `r.-1.1.mca` to `r.1.3.mca` will move it +1024 on both axis.

**Comment by maxsupermanhd** [comment]
Damn did not though about it at all. Maybe I will write something that will do that...
