### ISSUE TITLE
[Feature Request] Download item frames and armor stands.

### ISSUE THREAD

**Issue by questforboobs** [mircokroon/minecraft-world-downloader#19]
They are heavily used by builders to add details to builds; item frames and custom maps are used for custom paintings, while armor stands can be made to hold items and become invisible to have items as part of the build without being in a block (there's an Armor Stand Book datapack that is used for this).

**Comment by mircokroon** [comment]
This is mostly a bug actually, the code for doing this is already implemented (but evidently not really working).
