### ISSUE TITLE
An error has occured Right click settings to view

### ISSUE THREAD

**Issue by TDLAXD** [mircokroon/minecraft-world-downloader#193]
**Describe the bug**
its an error that says "An error has occured Right click settings to view"

**Steps to reproduce**
i just downloaded it and then i got it

**Log output**
```
my game did no crash     
...

```
**Screenshots**
ill send a screenshot = ![ghg](https://user-images.githubusercontent.com/89177835/130007241-68d279d2-e221-4b6b-b31e-d1e162138c4e.PNG)

**Version**
 - Game: Minecraft 1.17.1
 - Downloader: latest
 - Launcher (if login issues): 14.2

**Comment by mircokroon** [comment]
I think this is fixed now on the latest release, let me know if you still experience any issues.

**Comment by froggygroggy** [comment]
i am having this issue now.

1.19
