### ISSUE TITLE
Nether & end dimensions

### ISSUE THREAD

**Issue by mircokroon** [mircokroon/minecraft-world-downloader#2]
Entering a different dimension will currently lead to parsing errors. They should be handled correctly and saved in different region files than the regular world.

**Comment by IronException** [comment]
do they get saved in the overworld region then?

**Comment by mircokroon** [comment]
@IronException they do, the current issue is that no distinction is made between the dimensions so going into the nether may override chunks from the overworld if they are the same coordinates. All chunks are saved as if they are overworld chunks.
