### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by yoyo3841** [mircokroon/minecraft-world-downloader#211]
I try and run world-downloader.exe but all it gives is 2 error messages
![image](https://user-images.githubusercontent.com/83824884/132743451-a84ac2b6-1db2-4b89-a33f-85c31e8c4cff.png)
![image](https://user-images.githubusercontent.com/83824884/132743475-90e74f22-5693-4c27-82bc-acad3abd791a.png)
How do I use the tool?

**Comment by mircokroon** [comment]
You could try running the .jar, this might mean you don't have Java installed, or you might have an older version

**Comment by yoyo3841** [comment]
Update: I got it working, I didn't have java 16, installed, thought I did as I just updated to the most recent java version.
Though it does only work when I run the .jar, .exe gives the same errors

**Comment by Xulum12** [comment]
I have this problem too, but i have the newest version (16) can someone help me? I want to save an old server what is dying.

**Comment by mircokroon** [comment]
Make sure that you have the latest Java version, if that doesn't fix it you can try removing older version to see if that makes it work. 

You can also try running the .jar file through the commandline, that usually works.

**Comment by Xulum12** [comment]
I have the latest version, and I removed the old versions. And the cmd is somehow nac't run it.

**Comment by mircokroon** [comment]
Try running `java -version` to see if the version is correct

**Comment by Xulum12** [comment]
i can't open the java cmd but i have a program wich shows what version is java in so its 100% and i downloaded it from the java vebsite

**Comment by mircokroon** [comment]
It may not be installed correctly then. I suggest removing it and reinstall it.

**Comment by EinfachBen03** [comment]
I had Java 1.8.0 installed and every time I reinstalled it I got the same version (chose 64bit offline on the Website.) The Jar and exe didn't work. When I tried to start from the console it gave an error code I searched up.
