### ISSUE TITLE
Feature Request: Record player movements

### ISSUE THREAD

**Issue by DillFrescott** [mircokroon/minecraft-world-downloader#217]
Not sure how feasible this is, but I'd absolutely love a mod that can record player movements and actions but allow you to walk around in the replay like normal.

Sorry if this isn't really possible to do. :)

**Comment by mircokroon** [comment]
I'm not sure if this is really within scope of this application, but there is a replay mod available: https://www.replaymod.com/

**Comment by DillFrescott** [comment]
Thank you for the information!
