### ISSUE TITLE
Does this work with microsoft accounts?

### ISSUE THREAD

**Issue by AdyaGD** [mircokroon/minecraft-world-downloader#218]
I tried adding the microsoft access token and it doesnt work, only seems to work on mojang accounts which is very annoying for me

**Comment by mircokroon** [comment]
It's been confirmed to work with Microsoft accounts, at least using the normal automatic authentication. What kind of issue do you have?

**Comment by AdyaGD** [comment]
the auth key is either shorter or longer than 308

**Comment by mircokroon** [comment]
Right, I guess there's still an old check in the manual auth code from before Microsoft accounts. I'll release a fix for it. I think in most cases though the automatic auth works fine nowadays.

**Comment by mircokroon** [comment]
Should be fixed in the latest release.
