### ISSUE TITLE
how do i work this

### ISSUE THREAD

**Issue by tradermonkey** [mircokroon/minecraft-world-downloader#227]
i dont know how this works and i cant find any tutorials online 

this is what i have so far:
![Screenshot 2021-10-15 at 10 09 56](https://user-images.githubusercontent.com/92592531/137510516-6d795701-3733-4cd8-b6fd-5c8c1f21676e.png)

**Comment by mircokroon** [comment]
Well, yeah. It looks like you started it correctly, so the next step is to simply connect to the server `localhost:25565` in Minecraft.
