### ISSUE TITLE
Default Gamerules to values that won't modify the world

### ISSUE THREAD

**Issue by leumasme** [mircokroon/minecraft-world-downloader#24]
I think it would be a good idea to let all gamerules of downloaded worlds default to values that minimize change of the world to preserve the state that the world was downloaded in.
This would include
- random tick speed 0
- domobspawning false
- daylightcycle false
- weathercycle false
- mobgriefing false

**Comment by mircokroon** [comment]
Good idea, should be pretty quick to add.

**Comment by mircokroon** [comment]
I went with this selection, I don't think daylight cycle is very useful as this information isn't based on the server anyway.
![image](https://user-images.githubusercontent.com/23699979/85919654-9b058e00-b86d-11ea-9b6c-a7f1d0ce3940.png)
