### ISSUE TITLE
Downloaded world file is missing terrain

### ISSUE THREAD

**Issue by ZenFroot** [mircokroon/minecraft-world-downloader#240]
I got the world downloader to work, then pressed "Save overview to file" and then "Save & Exit" to get the world folder in my downloads folder. I then placed it into the Minecraft saves folder in %appdata% and tried opening it in singleplayer. The "Experimental Features" warning popped up and after getting past it, the world file did not load in any blocks. The world only contains the void. I have gotten the world downloader to work but I'm not sure what I'm doing now that's causing the issue.

**Comment by mircokroon** [comment]
Are you sure you were in the correct location, and in the correct game version?

**Comment by ZenFroot** [comment]
> Are you sure you were in the correct location, and in the correct game version?

Yes and yes. Travelled around the area I wanted to download and used the latest release on 1.17.1.

**Comment by ZenFroot** [comment]
Fixed by clicking the option to respawn, the world places you back where you logged off the server and ended the download process.
