### ISSUE TITLE
--minecraft-dir flag request

### ISSUE THREAD

**Issue by AronDev** [mircokroon/minecraft-world-downloader#243]
Hello.
In the README there is an optional flag named _--minecraft-dir_ (default: %appdata/.minecraft), but it is not implemented yet I guess?
Can you make it work because there are custom launchers where there is a different folder name and you cannot change it?

**Comment by mircokroon** [comment]
Ah I guess the readme is out of date, this used to be used for the previous method of handling authentication. There's a wiki page on it but for some custom launchers it's a little bit out of date as well. 

https://github.com/mircokroon/minecraft-world-downloader/wiki/Authentication

**Comment by AronDev** [comment]
I tried to find _./{mc}/launcher_accounts.json_ but there is no file named that. Also I tried the _wmic_ command in terminal but there is no accessToken row. Maybe there are some form of security in the launcher against this program?

**Comment by mircokroon** [comment]
What launcher are you using?

**Comment by AronDev** [comment]
I am using MesterMC.

**Comment by mircokroon** [comment]
Ah, I'm not familiar with this launcher but it's possible it uses a different method than the default launcher which is not currently supported by this application.
