### ISSUE TITLE
How do I set this up on a second computer

### ISSUE THREAD

**Issue by mianderson2469** [mircokroon/minecraft-world-downloader#244]
My computer cannot run this software and minecaft.  I would like to have this on my second computer running and the computer that I am playing minecraft on will connect to the second computer and not Localhost

**Comment by mircokroon** [comment]
This is possible, you'll have to manually get the authentication details over to the second computer and connect to the other device's local IP instead of localhost.

**Comment by mianderson2469** [comment]
I have not been able to get it to work yet.  Any idea how I would go about doing that?

**Comment by Jannik-06** [comment]
If your two computers are in the same network and If your on windows on the second computer(the one with the downloader) you can find your local ip adress by opening cmd by searching it in the search bar. Then in cmd type ipconfig there shoud be something called the iPv4 adress that is what you have to connect to in minecraft

**Comment by rautamiekka** [comment]
> ipconfig

Linux (and I imagine Mac) equivalent: `inet` value from `ifconfig` or `ip -family inet addr` for an interface that's not called `lo`; the `inet` value will have a trailing `/X` where `X` is an integer, those need to be dropped.
