### ISSUE TITLE
Make it so that command block commands are stored

### ISSUE THREAD

**Issue by CommandCracker8** [mircokroon/minecraft-world-downloader#245]
My friend has a command block server and I want to download it all (for him because his internet is pretty bad) but this program doesn't store command block data. I've tried changing it to do that but I haven't managed to find the appropriate class :|

**Comment by mircokroon** [comment]
If this is supported at some point, it would still require opening every single command block to get the data from them so it's not really something that's easily done through a world-downloader application.

**Comment by CommandCracker8** [comment]
Hmmm OK, what about entity NBT? It seems that isn't being stored either.
