### ISSUE TITLE
Support Minecraft 1.18

### ISSUE THREAD

**Issue by mircokroon** [mircokroon/minecraft-world-downloader#251]
- [x] Downloading blocks
- [x] Handling biomes correctly
- [x] Entites/Block entities
- [ ] Render distance extending
- [x] Block changes in loaded chunks

**Comment by Staninna** [comment]
I'm hyped for this update

**Comment by samiham2** [comment]
Whats the ETA on this one :) really wannna use it. Not super into java dev but if you need help woth anything send me an email samielimam@gmail.com

**Comment by mircokroon** [comment]
Here's a pre-release for 1.18, supporting at least the core functionality. Will probably take at least a few weeks before I can get around to fixing the rest. 

https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.15

**Comment by Staninna** [comment]
Hell yeah a pre release

**Comment by Sickjuicy** [comment]
> 

I have a problem 

Fehler: Beim Laden der Klasse Launcher ist ein LinkageError aufgetreten
        java.lang.UnsupportedClassVersionError: JVMCFRE003 Ung³ltige ³bergeordnete Version; Klasse=Launcher, Offset=6

**Comment by Fisherman1110** [comment]
Please update for 1.18.2 I love this program

**Comment by KunoiSayami** [comment]
1.18.2 is working properly.
