### ISSUE TITLE
This application requires a Java Runtime Environment 16

### ISSUE THREAD

**Issue by Shizzins** [mircokroon/minecraft-world-downloader#252]
No matter how much I updated Java, it will keep saying I need Java Runtime Environment 16. Is there a fix to this?

**Comment by mircokroon** [comment]
Try removing any old Java versions you might have installed, sometimes it'll try to pick those over the correct version.

Alternatively you can try adjusting the JAVA_HOME and (both user and system) PATH environment variables to point to the correct installation.
