### ISSUE TITLE
MC gives error while trying to connect to localhost

### ISSUE THREAD

**Issue by BeezlyJackal** [mircokroon/minecraft-world-downloader#255]
![image_2021-12-05_015519](https://user-images.githubusercontent.com/95561490/144736886-3934cee1-2efc-481b-bfbc-ea049d1401cb.png) i attempt to connect to the local host after setting up the downloader, and i get this error message in MC

**Comment by mircokroon** [comment]
What game version is this?

**Comment by BeezlyJackal** [comment]
1.18. should have said that.

**Comment by mircokroon** [comment]
1.18 is not currently supported, see #251

**Comment by BeezlyJackal** [comment]
Ah. Thank you.
