### ISSUE TITLE
Allow connecting to offline-mode servers

### ISSUE THREAD

**Issue by NickAcPT** [mircokroon/minecraft-world-downloader#26]
I think it would be nice to also be able to download the worlds off of an offline mode server.

For this, no authentication is needed through Mojang and encryption is totally disabled[(source)](https://wiki.vg/Protocol_FAQ#Offline_mode).

**Comment by mircokroon** [comment]
Doesn't this already work? The authentication code is pretty reactive to what the client and server do, if they send no encryption request then it's not used.

**Comment by NickAcPT** [comment]
I didn't try this yet, so I assumed that it wasn't implemented.
Closing since it is most likely implemented.
