### ISSUE TITLE
i keep getting JNI and i only have java 16 nothing else

### ISSUE THREAD

**Issue by NicholasDIp** [mircokroon/minecraft-world-downloader#265]
i installed java 16 and made sure it works and then installed world downloader and it still dosnt work

**Comment by mircokroon** [comment]
Try removing any old Java versions you might have installed, sometimes it'll try to pick those over the correct version.

Alternatively you can try adjusting the JAVA_HOME and (both user and system) PATH environment variables to point to the correct installation.
