### ISSUE TITLE
Implement protocol version translation

### ISSUE THREAD

**Issue by NickAcPT** [mircokroon/minecraft-world-downloader#27]
I think this project would benefit from allowing users to join to servers with versions that aren't supported out of the box by making use of some project like ProtocolSupport or ViaVersion.

**Comment by mircokroon** [comment]
Could you specify what you mean by this? What specific version(s) would this add support for?

**Comment by NickAcPT** [comment]
Well, ViaVersion usually supports newer versions to connect through a specific version (say 1.15.2).
Then there's ViaBackwars and ProtocolSupport which would allow to join older clients to servers with newer versions (say 1.8 client joins a 1.15.2 server).

**Comment by mircokroon** [comment]
It will currently just use whatever protocol version the server/client agree on, I assume that this will work fine with those? I've tested it on at least one server that lets a large number of client versions connect and it works fine. Did you try this and find it to not work? What was the specific setup there?

**Comment by NickAcPT** [comment]
> Did you try this and find it to not work?
I did try it out and it works just fine. But I thought it would be helpful to have when there are client-server versions mismatch.

**Comment by mircokroon** [comment]
Don't the client and server still communicate in a single protocol version in this case? As far as I know, for this to work either the client or the server (usually the server) just uses the version that the other is using. The downloader would not work if the client and server use a different version, but I don't think this happens anywhere. 

I believe this is a case that's already supported by default. Unless there is a specific case you are aware of (e.g. specific versions of Minecraft and any plugins being used by both server and client) where there are problems, I don't think there is anything that needs to be changed in this application to support this.

**Comment by NickAcPT** [comment]
Oh, that makes sense. Closing as it is already a thing.
