### ISSUE TITLE
Is 1.18.1 supported at all yet?

### ISSUE THREAD

**Issue by KapDEK** [mircokroon/minecraft-world-downloader#271]
I saw that 1.18 recieved partial support, but when I tried this for 1.18.1, it failed? Is it supported yet?

**Comment by mircokroon** [comment]
1.18 is not yet supported. See #251

**Comment by KapDEK** [comment]
how long do you think until it will be supported?

**Comment by mircokroon** [comment]
Could be a few days, could be a few months. I can't say.
