### ISSUE TITLE
Having Java problems in version 1.16

### ISSUE THREAD

**Issue by javierlm96** [mircokroon/minecraft-world-downloader#28]
I'm launching the tool with this command _java -jar world-downloader.jar --server ********* --port ******_ and when I attach the session with the Minecraft executable nothing appears in the Wold Downloader window. The game runs without problems, but the world folder is empty. Also tried as sudo to avoid permission issues. Minecraft version: 1.16

Thank you in advance

 <img width="1206" alt="Captura de pantalla 2020-06-27 a las 16 50 36" src="https://user-images.githubusercontent.com/60676107/85925136-ba64e100-b896-11ea-8ad2-c60dc6e1abff.png">

**Comment by mircokroon** [comment]
It looks like the protocol doesn't match. Are you using the latest release of the world downloader? I think this should be fixed in the [latest version](https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.5).

**Comment by jlaserna** [comment]
I’m using the latest version, the 1.5

**Comment by javierlm96** [comment]
Yes, I’m using the latest release: 1.5

**Comment by mircokroon** [comment]
Aah I see, you must be using version 1.16.0 instead of 1.16.1. It should be fixed now, thanks for the report!

https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.5.1
