### ISSUE TITLE
This Application requires a java runtime environment 16

### ISSUE THREAD

**Issue by furydeath9** [mircokroon/minecraft-world-downloader#287]
I've tried updating it from the site it sends you to but  then it just give you the same This Application requires a java runtime environment 16

Recommended Version 8 Update 311 (filesize: 81.71 MB)
Release date October 19, 2021

**Comment by furydeath9** [comment]
Tried using older verison and it can't even connect to a sever but at least it still can be  open

**Comment by fixelgrillex** [comment]
maybe this can help, try to download it. https://adoptium.net/?variant=openjdk17&jvmVariant=hotspot for me it now works just fine

**Comment by mircokroon** [comment]
Depending on how it's installed the old Java versions may sometimes be used instead so it could be worth removing those as well. 
https://github.com/mircokroon/minecraft-world-downloader/wiki/FAQ
