### ISSUE TITLE
1.15 pre-release won't open

### ISSUE THREAD

**Issue by burn333** [mircokroon/minecraft-world-downloader#291]
Installed 1.15 pre-release for Minecraft 1.18.1 and have re-installed java yet it doesn't open or give me an error message at all when trying to start the program.

**Comment by mircokroon** [comment]
Any more information? Can't really do much with no error or anything like that. You could try running the .jar file over the commandline instead if you're not already.

**Comment by burn333** [comment]
Oh the .jar loaded up fine thanks. The .exe file still won't open for some reason and it doesn't give me an error or any information.
