### ISSUE TITLE
Connect to a replay?

### ISSUE THREAD

**Issue by ItsEternis** [mircokroon/minecraft-world-downloader#294]
Much like the title says I'm attempting to connect it to a replay due to a friend losing the actual world itself, the replay counts as a world but I can't figure out how/if it's possible to connect the world downloader to it. This is the only world downloader I've found available for 1.17 so all my marbles are kinda rolling on it.

**Comment by XanderStoffels** [comment]
Can you give some more info about a replay? I'm assuming it is a mod. What kind of file/folder structure does it have?

**Comment by ItsEternis** [comment]
> Can you give some more info about a replay? I'm assuming it is a mod. What kind of file/folder structure does it have?

It's just the general replay mod you find at replaymod.com. Not too sure how to describe the file/folder structure but it essentially loads you into the world, I'm not too sure how to explain it it's 5 in the morning and been a long night of trying things.

**Comment by XanderStoffels** [comment]
Could you share the replay so we can take a look at it.

**Comment by ItsEternis** [comment]
My friend isn't wanting to give out the actual replay of the build itself but here's an example one which should work all the same. Since it's not a regular file type I'm sharing it through drive.
https://drive.google.com/file/d/1am4OYpUntzvPJBTDpTcJxW-O4py09m5O/view?usp=sharing

**Comment by XanderStoffels** [comment]
The ZIP contains metadata which points to the world you've made the recording in, but It does not look like the world is included in the ZIP you've sent me. I don't think we will be able to help.

[recording.tmcpr.zip](https://github.com/mircokroon/minecraft-world-downloader/files/7866148/recording.tmcpr.zip)

**Comment by ItsEternis** [comment]
The replay is able to be played without the world itself, when I deleted the world the replay still loads up just fine.

**Comment by XanderStoffels** [comment]
Well I downloaded the mod to try it out, but it can not read the file you provided because it is a tmcpr file, which means your recording did not save correctly. After going though [this thread](https://www.replaymod.com/forum/thread/1059) I converted the file to a mcpr file, but on loading that file my game crashed. 🤷‍♂️ 

I suggest that you go to the replaymod forums and ask the people there if you can recover the world from a replay, because this is getting a bit out of scope for this repo.

**Comment by mircokroon** [comment]
Yeah I don't think this is really in scope either so I'll close this
