### ISSUE TITLE
I run the .exe and get a error

### ISSUE THREAD

**Issue by 6351** [mircokroon/minecraft-world-downloader#295]
When I run the .exe I get this error 

Error: A JNI error has occured, please check your installation and try again

I click okay and get this error

A Java Exception has occured

**Comment by XanderStoffels** [comment]
If you open a command prompt and type `java --version`, what do you get?

**Comment by mircokroon** [comment]
See the [FAQ](https://github.com/mircokroon/minecraft-world-downloader/wiki/FAQ)
