### ISSUE TITLE
Can only use this to download the world of a server with online mode off

### ISSUE THREAD

**Issue by szalony9szymek** [mircokroon/minecraft-world-downloader#30]
Is there any fix? When i join i get a "Disconnected" in minecraft after "Logging in..." for a long time, while in the console i get this:
C:\Users\Administrator\Downloads>java -jar world-downloader.jar -s hypixel.net
Starting proxy for hypixel.net. Make sure to connect to localhost:25565 instead of the regular server address.
Cannot connect to hypixel.net. The server may be down or on a different address.

It works fine on cracked servers(ones with online mode off) , so it must be an authentication bug(yes, I am using an original copy of the game). I am on 1.12.2

**Comment by mircokroon** [comment]
I think the issue might be that the actual IP is `mc.hypixel.net`, not `hypixel.net`.

**Comment by szalony9szymek** [comment]
Both are correct

**Comment by szalony9szymek** [comment]
Tomorrow I will try with a server with no pluginb(that might be the issue)

**Comment by mircokroon** [comment]
I suggest you try `mc.hypixel.net` instead. When I try it myself `mc.hypixel.net` works fine but `hypixel.net` leads to the problems you described.

**Comment by mircokroon** [comment]
I looked into it a bit more, it has to do with Minecraft usually automatically redirecting you to `mc.hypixel.net` while the world downloader does not. A workaround is to just use `mc.hypixel.net` as IP for the world downloader.

I created issue #31 to more accurately describe the issue, I'll close this.

**Comment by szalony9szymek** [comment]
thanks, it works
