### ISSUE TITLE
Internal Exception

### ISSUE THREAD

**Issue by djghju4645** [mircokroon/minecraft-world-downloader#311]
![image](https://user-images.githubusercontent.com/98405858/150997104-d9062f2b-4f19-4d05-9645-1d93ebf632c7.png)
this is after connecting and setting up

**Comment by alexpearce92** [comment]
Same for me. Happened after I tried to connect to a server while I was using the 1.18.1 launcher. Did not exist in the 1.17.1 launcher.

**Comment by AbdykerimovUrmat** [comment]
1.18.1 same

**Comment by Hyperbus02** [comment]
happens to me aswell

**Comment by MrAxeTv** [comment]
Getting same error in launcher and this in terminal out put https://pastebin.com/aiM7jtwv

**Comment by martijn-heil** [comment]
What version are you guys using exactly? With what version of the minecraft client, and what version of the server you're connecting to?
And furthermore, on what system are you?

I haven't been able to reproduce this error on my system so far.


world downloader version: 1.15 pre-release
Minecraft client and server version: 1.18.1

OS: Arch Linux

Java version: 
```
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12)
OpenJDK 64-Bit Server VM (build 17.0.1+12, mixed mode)
```

**Comment by MrAxeTv** [comment]
> What version are you guys using exactly? With what version of the minecraft client, and what version of the server you're connecting to? And furthermore, on what system are you?
> 
> I haven't been able to reproduce this error on my system so far.
> 
> world downloader version: 1.15 pre-release Minecraft client and server version: 1.18.1
> 
> OS: Arch Linux
> 
> Java version:
> 
> ```
> openjdk version "17.0.1" 2021-10-19
> OpenJDK Runtime Environment (build 17.0.1+12)
> OpenJDK 64-Bit Server VM (build 17.0.1+12, mixed mode)
> ```

So I was testing on  1.18.1 and 1.18 
Server is play.originrealms.com
Windows 10
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-39)
OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)
and I tried to use it with latest jars from github provided by links I asum that is 1.15 pre-Release 
because in your app there is no way to see version number or maybe I am wrong and I didn't notice there is that info
