### ISSUE TITLE
Download a Server World

### ISSUE THREAD

**Issue by Brack04NC** [mircokroon/minecraft-world-downloader#319]
Is possible to download a Server world (a multiplayer world, not my localhost host world server)?

**Comment by martijn-heil** [comment]
> 

Yes, this program continuously saves chunks that are sent to your Minecraft client by the server to disk. Or to put it another way; it continuously downloads whatever is in your render distance.


To download an entire world you need to travel through the whole world, having had every single chunk within your render distance and thus downloaded and saved to disk.
