### ISSUE TITLE
Disable world generation

### ISSUE THREAD

**Issue by szalony9szymek** [mircokroon/minecraft-world-downloader#32]
I saw that one mod had an option that disable world generation(useful for example if you downloaded your skyblock island from a server). This tool just generates a world in empty chunks - https://i.ibb.co/j6ty8k1/example-skyblock.png

**Comment by szalony9szymek** [comment]
Another example: https://i.ibb.co/q7qr7tF/example2.png

**Comment by mircokroon** [comment]
Implemented now, thanks for the suggestion.
