### ISSUE TITLE
"Connection Lost" when connecting to localhost

### ISSUE THREAD

**Issue by lululock71** [mircokroon/minecraft-world-downloader#325]
**Describe the bug**

After lunching the world-downloader.jar, connecting the Minecraft client to localhost:25565 yields to a "Connection Lost" error from the client.

world-downloader output :
`Login success: XXX logged in with uuid XXX`
`Using protocol of game version 1.17 (757)`
`Client probably disconnected. Waiting for new connection...`

**Steps to reproduce**

1. Start world-downloader : `java -jar world-downloader.jar -s SERVER_ADDRESS`
2. Connect to `localhost:25565` or `127.0.0.1:25565` in the MC client
3. Wait a few seconds to get the error

**Version**

 - Game: Minecraft 1.18.1 (with some Fabric mods + Optifine)
 - Launcher : TLauncher 1:1.132.0-1
 - OS : ArchLinux

**Comment by GoodGolem** [comment]
I also encounted the same issue hopefully the devs come to fix this fast

**Comment by GoodGolem** [comment]
I am using windows 11 btw

**Comment by GoodGolem** [comment]
Oh it says at #251 it isn't great yet... It is just a prerelease.

**Comment by GoodGolem** [comment]
So lets just wait until it is great

**Comment by slipprs** [comment]
How do you connect to localhost?
