### ISSUE TITLE
Internal Exception

### ISSUE THREAD

**Issue by xXTronXx3971** [mircokroon/minecraft-world-downloader#336]
When trying to connect through localhost an internal exception error occurs.

![image]([](https://user-images.githubusercontent.com/37986534/161444383-02fd9e11-3dd8-4ba3-89a4-60e28be7bbfb.png))

**Comment by xXTronXx3971** [comment]
Used wrong version of wdl

**Comment by froggygroggy** [comment]
i am having this issue. i have the most recent version
