### ISSUE TITLE
Client not authenticated issue

### ISSUE THREAD

**Issue by appletechgeek** [mircokroon/minecraft-world-downloader#342]
heya good day. i got a odd issue.,

i seem to be unable to get authenticated! 

i tried to find my access token both with multimc and the Minecraft launcher but it does not appear to take it and still gives me the error.

for the official Minecraft launcher all the token says is [] in the json file.

if I use the powershell method and copy the token it still gives me the same error.

same with any of the tokens in the accounts.json for multimc. 

what can I do?

for reference I indeed do have a migrated microcrap account.

**Comment by koendecouck** [comment]
I just got it working with MultiMC. It's probably the token. Check the accounts.json file, and note that it actually has multiple tokens in it. The last one at the bottom worked for me, but you could just try them all.
