### ISSUE TITLE
Connection lost when joining the localhost

### ISSUE THREAD

**Issue by MrSkills93** [mircokroon/minecraft-world-downloader#350]

**Comment by Orionpax2** [comment]
Did you ever manage to fix the issue? if so how did you do it? I currently face the same annoyance

**Comment by MrSkills93** [comment]
@Orionpax2  Well i have 1 good and 1 bad news, first is that yes I did managed to fix the issue and now it works fine. Second is that i don't remember how did i do it. I can't really help you just make sure you have the right minecraft version and search for other people with the same issue. I do remember that it didn't last very long and that it was easy to remove, it might even fix itself with time.
