### ISSUE TITLE
World only copies entities

### ISSUE THREAD

**Issue by BENNNNZO** [mircokroon/minecraft-world-downloader#362]
When trying to copy the world everything goes smoothly and the world top view map even appears in the GUI but when I load into the world only things like armor stands really copy over.

I believe it could be caused by my VPN but I recently had a problem with my ISP and can only use Minecraft servers if my VPN is connected and set to an OpenTCP protocol.

I'm not sure how to check the log so if that would help just let me know and I can provide that also.

-- Here are some screenshots of the issue --

![Capture](https://user-images.githubusercontent.com/106880823/172016266-4d0bbc59-d21d-486e-a1fd-589c97f7d75d.PNG)
![2022-06-04_12 27 54](https://user-images.githubusercontent.com/106880823/172016271-9e02d606-b8ab-472f-af93-4decaf2c1256.png)

 - Game: Minecraft 1.18.0
 - Downloader: latest

**Comment by mircokroon** [comment]
This issue happens on some non-standard servers, so unrelated to your internet settings at least.

**Comment by BENNNNZO** [comment]
yea thats interesting I tried 4 other servers and it did the same thing. I even tried hypixel lobbies but when I tried my hypixel SMP server it worked!

still having sometrouble with the seed which may be because i used an amplified world but ill keep testing different things and see
