### ISSUE TITLE
Compile error . please update compile instructions and dependencies

### ISSUE THREAD

**Issue by Tsoccerguy3** [mircokroon/minecraft-world-downloader#363]
**Describe the bug**
Compile error

**Steps to reproduce**
Compile from scratch JDK 18

**Log output**
```
https://github.com/mircokroon/minecraft-world-downloader/files/8839022/compile.log.txt

**Comment by Ravendwyr** [comment]
This project requires JDK 17 to compile and run.

**Comment by Tsoccerguy3** [comment]
Ok , thank you for clarification . I thought Java 17JDK was set at the minimum version and would compile with newer JDK versions

**Comment by Ravendwyr** [comment]
Sadly it doesn't always work like that. It's looking like JDK18 removed or changed something that this project uses in JDK17 which prevents it from compiling successfully.

**Comment by Tsoccerguy3** [comment]
I will now close this issue as works as intended with JDK 17
