### ISSUE TITLE
Some random chunks do not get saved , even after multiple attempts

### ISSUE THREAD

**Issue by Tsoccerguy3** [mircokroon/minecraft-world-downloader#367]
**Describe the bug**
Random chunks wont save no matter how many times tried

**Steps to reproduce**
Nothing done out of the ordinary

**Log output**
```
[saved.log](https://github.com/mircokroon/minecraft-world-downloader/files/8840211/saved.log)

...

```
**Screenshots**
![2022-06-05_10 31 35](https://user-images.githubusercontent.com/22108822/172056712-2e58fa5d-8283-416d-931e-4764bda8d4a4.png)
![2022-06-05_10 31 50](https://user-images.githubusercontent.com/22108822/172056715-eb7369d9-9796-4d95-8918-51c317f72d42.png)

**Version**
 - Game: Minecraft 1.18.2
 - Downloader: latest
 - Launcher (if login issues): 14.2

**Comment by Tsoccerguy3** [comment]
I opened the map in Amulet to see if i could see any odd blocks. Looks like downloader begins to save blocks , but there is something in that space that downloader is not handling . Then when I open in single player minecraft resets the chunk because its a bad chunk save

![amulet](https://user-images.githubusercontent.com/22108822/172070085-f047d28c-105a-4a1b-baa0-c0ced3cd3964.PNG)
![amulet2](https://user-images.githubusercontent.com/22108822/172070087-1bf8c74b-4a94-441c-bb6c-57662291390e.PNG)
![amulet3](https://user-images.githubusercontent.com/22108822/172070088-8978aea8-d9c3-4bba-b252-75dcafb068b2.PNG)
![amulet4](https://user-images.githubusercontent.com/22108822/172070089-5e606963-9cb5-4abf-b003-0933cee9a82e.PNG)

**Comment by mircokroon** [comment]
Hmm, could you give this release a try? Not sure if it fixes these issues or if its something else.

https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.16_b

**Comment by Tsoccerguy3** [comment]
v1.16_b , no change 
![2022-06-05_18 45 17](https://user-images.githubusercontent.com/22108822/172073764-5735588c-5c20-4a08-9341-49ed8379d1e6.png)

**Comment by Tsoccerguy3** [comment]
Is there any debugging that can be turned on?

**Comment by mircokroon** [comment]
There is some but it's quite involved. I _think_ I know what the issue is, does Minecraft give any errors when loading into the world?

**Comment by Tsoccerguy3** [comment]
Here is the log when joining the world
[latest.log](https://github.com/mircokroon/minecraft-world-downloader/files/8841194/latest.log)

**Comment by LordVertice** [comment]
Had a similar issue some time ago, don't have the logs right now. Could this be caused by not stopping the WDL correctly? I'm never quite sure if I should disconnect first and then safe+quit in WDL or the other way around. Perhaps doing it the wrong way interrupts the program and causes some chunks to break?

**Comment by Tsoccerguy3** [comment]
I deleted the chunks and tried again . This time a chunk that was copied in the past , did not get copied this time . the hole in center

![2022-06-06_15 25 39](https://user-images.githubusercontent.com/22108822/172233097-e19cd97e-26b4-4f83-aabc-0ab95fe9d75b.png)
![2022-06-06_15 25 41](https://user-images.githubusercontent.com/22108822/172233101-3a66c2f6-c139-4b94-aaf2-23524bf1bd29.png)

**Comment by Tsoccerguy3** [comment]
![2022-06-06_15 33 18](https://user-images.githubusercontent.com/22108822/172234278-9ac4a903-8fac-43e5-8b35-32fdb076827d.png)

**Comment by mircokroon** [comment]
Hmm seems to complain about banners, although those should prevent the entire chunk from loading. I guess the server might send banner entities for places where there isn't a banner block. 

Can you check with NBT edit if one of those chunk sections that's missing has any data set at all?

**Comment by Tsoccerguy3** [comment]
I will do better , a quick save that i don't open

**Comment by Tsoccerguy3** [comment]
[fabmap.zip](https://github.com/mircokroon/minecraft-world-downloader/files/8847325/fabmap.zip)

**Comment by mircokroon** [comment]
Looks like it just saved nothing for those sections, strange. Added some logging for one of the chunks that's broken, can you try running with this version and sending the log output?

https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.16_d

**Comment by Tsoccerguy3** [comment]
[fabmapv1.16_d.zip](https://github.com/mircokroon/minecraft-world-downloader/files/8848425/fabmapv1.16_d.zip)
[latestv1.16_d.log](https://github.com/mircokroon/minecraft-world-downloader/files/8848427/latestv1.16_d.log)

**Comment by mircokroon** [comment]
I mean the downloader log, should have printed some stuff in the error log I think

**Comment by Tsoccerguy3** [comment]
could not find a error log but i copied this from the error tab in settings

[downloadererror.log](https://github.com/mircokroon/minecraft-world-downloader/files/8848667/downloadererror.log)

**Comment by mircokroon** [comment]
Yes that's it, thank you. 

Alright I see what the issue is, will see if I can fix it.

**Comment by mircokroon** [comment]
Alright, hopefully last one:

https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.16_e

**Comment by Tsoccerguy3** [comment]
Fixed as far as I can see . Thank You . I will close this issue as fixed
