### ISSUE TITLE
Draw nearby existing chunks bug?

### ISSUE THREAD

**Issue by AgileGhost** [mircokroon/minecraft-world-downloader#374]
Hello, I labeled this as a bug but I'm not actually sure if this is a bug or not.

However, the "Draw nearby existing chunks" doesn't seem to do anything other than just turn the chunks from a pervious run completely black from their usual white colour on the preview. Which doesn't seem right, I thought it should draw the chunks already saved on the map preview. Which would be nice to have even have it shaded a certain colour to show its old.

How it usually looks.
![image](https://user-images.githubusercontent.com/61676371/172371035-4cd2d27d-5817-4808-9796-f69f14d0841f.png)

How it looks after clicking the button.
![image](https://user-images.githubusercontent.com/61676371/172370918-e1a95de2-d716-4fbb-b725-7c0631c03d9a.png)

I also got this small error on the console which isn't related to this bug report. 
```js
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @47d384ee'
```

I'm using ver. 1.18.2 and v1.16.2 of the downloader. 
p.s. Thanks for appreciate the work!

**Comment by Tsoccerguy3** [comment]
This feature is to extend you view distance from what the server sets around 10 chunks to what you set extend distance to. you need to set your view distance toa number 10 plus what you extend to . if its been saved you will see 16 chunks for example in game

**Comment by mircokroon** [comment]
I think this doesn't work yet on 1.18.2

**Comment by AgileGhost** [comment]
> This feature is to extend your view distance from what the server sets around 10 chunks to what you set extend distance to. 

Ohh, okay! I wasn't so sure about what it actually was. 

>I think this doesn't work yet on 1.18.2 

Yeah am aware, I've seen it work a few times but not all the time. But I didn't know it was that feature. 

Sorry for the late reply tho. Was busy. I'll close the issue since it's already known.
