### ISSUE TITLE
Show old chunks from previous run. 

### ISSUE THREAD

**Issue by AgileGhost** [mircokroon/minecraft-world-downloader#379]
After mentioning it in my previous issue of being confused about a feature. I'll like to request the feature I thought it was...

When relaunching or starting up a new session of the launcher, it will set the previous chunks to white [img 2] to show that they were saved at one point or another, I would like to see that instead of just white boxes that there will be an option or button to convert them back into a proper map with likely a white or gray overlay to show that they're older. [example img 3]

Saved chunks (before close)
![image](https://user-images.githubusercontent.com/61676371/172807943-882e7b2c-cd11-4dc7-a3e8-784d202b3bec.png)

Saved chunks (After close & new session)
![image](https://user-images.githubusercontent.com/61676371/172809656-e23d7f70-a5e7-4075-abf8-c4d997016253.png)

Preposed look instead of above (with toggle??)
![Untitled](https://user-images.githubusercontent.com/61676371/172809854-75faec35-dee4-42bb-b7e1-691033af31d5.png)

I believe this would be useful to look over the map to update "important-ish" stuff, know the surrounding area, etc and overall looks better than just white boxes. As such it isn't anything important so take your time.

**Comment by mircokroon** [comment]
That's sort of how it works on most versions except on 1.18 where its broken. It doesn't fade out the old chunks though, that is a good idea

**Comment by AgileGhost** [comment]
> That's sort of how it works on most versions except on 1.18 where its broken. 

I see, I thought it only extended render distance. Am also assuming it does it for the whole map. But yeah, I'd like to request the gray out if possible. (when its fixed... whenever. I believe 1.19 update is more important than a niche feature)
