### ISSUE TITLE
Application Requires Java Runtime Environment 17

### ISSUE THREAD

**Issue by Velocity1357** [mircokroon/minecraft-world-downloader#387]
When I try to launch gives this "Application Requires Java Runtime Environment 17" error and when I press ok it redirects me to the java download page which I proceed to download and install which it tell me it successful does.
But then still just returns to same error upon launch

![image](https://user-images.githubusercontent.com/107451511/173485412-90dccac3-a22b-4539-b40d-21019fc7d2c3.png)

**Comment by LordVertice** [comment]
Try this to see if Java 17 is installed correctly:

1. Press the Windows key
2. Type "cmd" in the search bar and open the first program (called command prompt)
3. In cmd, type "java --version" and hit enter
4. Show us the result, either copy paste or send a screenshot

**Comment by AgileGhost** [comment]
Sometimes you may need swap the version of Java that needs to be used, [This](https://www.happycoders.eu/java/how-to-switch-multiple-java-versions-windows/) may help

**Comment by mircokroon** [comment]
Easiest solution is to remove all older versions of Java that you have installed, if you don't need them for anything

**Comment by Velocity1357** [comment]
> Easiest solution is to remove all older versions of Java that you have installed, if you don't need them for anything

I have it is simply just the java that I was redirected to install that is installed. I did uninstall the rest...

**Comment by Velocity1357** [comment]
I resolved myself had to go find a different download for JDK 17, it redirected me to a normal java thing which didnt help whats so ever but is resolved now
