### ISSUE TITLE
Still Crashes in 1.19

### ISSUE THREAD

**Issue by mharbb** [mircokroon/minecraft-world-downloader#389]
When I join local Host the downloader crashes.

**Comment by LordVertice** [comment]
Happens to me too when trying to join a realm, same issue (and error) as #376. I'd reopen that, but it was closed by the PR merge so I can't.

**Comment by mircokroon** [comment]
Alright, I think this should work more consistently, made a pre-release if anyone wants to confirm

https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.16.4_a

**Comment by mharbb** [comment]
> Alright, I think this should work more consistently, made a pre-release if anyone wants to confirm
> 
> https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.16.4_a

How do I build it?

**Comment by LordVertice** [comment]
Don't worry about it, [there's a full release now](https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.16.4)
