### ISSUE TITLE
Some inventories not saving

### ISSUE THREAD

**Issue by mharbb** [mircokroon/minecraft-world-downloader#393]
The ender chest and player inventory are not properly saving.

**Comment by Tsoccerguy3** [comment]
The server does not send contents of chests unless you open the chest and commands from command blocks unless you have server perms to click and read them . This is not a BUG . If you want the contents click the chest on the server and if you have perms it will be saved .

NOT A BUG

**Comment by mharbb** [comment]
What about the player inventory not saving?

**Comment by mircokroon** [comment]
Player inventory saving is not supported.
