### ISSUE TITLE
Allow direct authentication if no launcher_profiles.json exists

### ISSUE THREAD

**Issue by BinaryEnigma01** [mircokroon/minecraft-world-downloader#4]
I'm running a twitch modpack, I know I can connect to the server because I just did so, after starting minecraft-world-downloader.jar with the same server address and adding localhost to the server list, it even shows the same server icon and motd, but when I try to connect to that one, I get "This server has mods that require FML/Forge to be installed on the client. Contact your server admin for more details.", Console running the jar says the same: `Performed handshake with (SERVER ADDRESS), protocol version 340 :: next state: login
Login by: BinaryEnigma
Disconnect: {"text":"This server has mods that require FML/Forge to be installed on the client. Contact your server admin for more details."}
Server probably disconnected. Waiting for new connection...` 
(Omitted the server address for security reasons)

**Comment by mircokroon** [comment]
Hey there, can you try this again on the latest version? I'm not able to reproduce this so it's possible it has been fixed already.

**Comment by mircokroon** [comment]
Alright I think I've found the issue and solved it. Are you able to connect now?

**Comment by BinaryEnigma01** [comment]
Now it just says "Disconnected", also it warned me that it couldn't find launcher_profiles.json because I'm using twitch so I added `-m "pathtotwitch/Install"`

**Comment by mircokroon** [comment]
It likely will not work with alternative launchers, unless they use the same format ```launcher_profiles.json```. If it does then it should work just fine, I can't really do anything about 'Disconnected' without an explanation from the server/client.

**Comment by mircokroon** [comment]
The solution here is probably to allow different authentication (e.g. username and password) when no relevant `launcher_profiles.json` can be found. Not really ideal for security but better than it not working at all in that case.
