### ISSUE TITLE
SSLHandshakeException on WSL

### ISSUE THREAD

**Issue by Fukastu** [mircokroon/minecraft-world-downloader#40]
I'm trying to get this to run on WSL due to problems with my Java installation. I'm runninng the command, which I'm pretty sure is right:

    java -jar world-downloader.jar -s server.ip -p 10200 -m /mnt/c/Users/Theo/AppData/Roaming/.minecraft --gui=false

It starts off fine:

    Starting proxy for server.ip:10200. Make sure to connect to localhost:25565 instead of the regular server address.             
    Performed handshake with server.ip:10200, protocol version 736 :: next state: login
    Login by: Fukastu    

But as soon as I try to connect to `localhost:25565`, it errors with:

    kong.unirest.UnirestException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Am I doing something wrong here? Any help would be greatly appreciated :)

**Comment by mircokroon** [comment]
Hmm strange, most likely it's unable to connect to the Mojang auth servers. Is there anything else to the error or just that line?

**Comment by ImUrX** [comment]
according to the issue that mirco mentioned, the fault was by kaspersky. did you try disabling the antivirus to see if its the one at fault :P

**Comment by Fukastu** [comment]
Sorry for abandoning this. Ended up being a misconfigured hosts file :/
