### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by cruc1b13** [mircokroon/minecraft-world-downloader#41]
Confused noob here,
This is the first time I've worked with Java executables, is there a certain folder I need to install them to? Does it function like a normal mod?

**Comment by ChillerDragon** [comment]
@cruc1b13 it is a external tool that acts as a proxy. So there is a "network" connection between this tool and your minecraft client. Which makes it path and client independent. So assuming you use windows? You download the java file and launch from a command prompt this command ``java -jar world-downloader.jar -s address.to.server.com`` make sure you are in the same directory with the command prompt where your world-downloader.jar is and replace address.to.server.com with the server you want to connect to. Then open your minecraft client and connect to localhost. This should then connect you to the downloader proxy you started which then connects to the server. Now all your minecraft traffic goes through the downloader and thats where it gets its data from.

**Comment by mircokroon** [comment]
I think this was explained pretty well so I'll go ahead and close it, feel free to ask if anything's still unclear.
