### ISSUE TITLE
World download

### ISSUE THREAD

**Issue by Beni-Benigno** [mircokroon/minecraft-world-downloader#42]
After I've run the program I do not understand where it is supposed to be found. 

I've clicked the button to save overview to file, but cant seem to find it.

Everything has gone flawless except the fact that i cant find level.dat.

**Comment by Beni-Benigno** [comment]
Sorry, I just found out where it is loaded, although it it a bit weird it is loaded in the system32 folder. 

Still when using the program the downloaded file will not be the one in the server. With world generation on it will be different and with it off it will be all void.

**Comment by mircokroon** [comment]
You can change where the world is saved using the ```--output``` argument. You've likely opened the terminal in the system32 folder for it to save there. 

It sounds like you might not be using the tool correctly. Note that the world is only downloaded in the area around the player. The save to overview option has nothing to do with the world itself, it only saves a picture of the overview map.
