### ISSUE TITLE
Stuck on encrypting and waiting for authentication

### ISSUE THREAD

**Issue by ninovd1** [mircokroon/minecraft-world-downloader#432]
Crash involving modified overworld dimensions, the server uses Terralith so perhaps that could be the problem?

Update: Photo of crash 
![afbeelding](https://user-images.githubusercontent.com/50085807/188014456-e616ccfa-5c7c-4f65-a76e-18cfbeb5491a.png)

**Comment by mircokroon** [comment]
Please use the issue template
