### ISSUE TITLE
Add an option to delete all previously downloaded chunks

### ISSUE THREAD

**Issue by sonekoo** [mircokroon/minecraft-world-downloader#44]
It would be nice to add an option to delete all previously downloaded chunks, when right clicking in the GUI for example. It could be useful when connecting to a server and then in a second map. That way we can delete everything and download the world we're in now.

**Comment by mircokroon** [comment]
Good idea!

**Comment by lucasparmentier** [comment]
Yeah, this is a great idea. Maybe it will be added in the next update? (if so, when pls :c)  :)
