### ISSUE TITLE
Problem with java.

### ISSUE THREAD

**Issue by Z1ppyX** [mircokroon/minecraft-world-downloader#445]
Issue: 
Everytime i run world downloader it says: "this applicacion requires java runtime environment 17 download" i tried to fix it but nothing worked.

how to achive bug:
Run world dowloader.

Image:
https://ctrlv.cz/z8El

 - Game: Minecraft 1.12.2
 - Downloader: latest

**Comment by XanderStoffels** [comment]
Have you tried downloading Java 17? Open a command prompt and run `java -version` to check which version you have.

**Comment by Z1ppyX** [comment]
> Have you tried downloading Java (JRE) 17? Open a command prompt and run `java -version` to check which version you have. This is most likely not a bug.

Oh thanks so much. :)
