### ISSUE TITLE
Give previously-downloaded chunks to the client allowing larger render distance

### ISSUE THREAD

**Issue by davr** [mircokroon/minecraft-world-downloader#47]
A really cool feature enhancement would be if the client's render distance is larger than the server's view distance, to provide cached chunks to the client so you can see further on multiplayer servers than you might otherwise be able to. Yes these chunks will be out of date, but they're far away and will update when you get closer.

I've got a fast computer and like to play with render-distance = 32 on single player worlds, but often times servers have it set much lower to reduce their cpu/bandwidth costs (I believe 10 is the default).

This would allow me to get the farther view distance without any cost to server operators!

Here's an example that hopefully explains the idea better:
![image](https://user-images.githubusercontent.com/321552/87985928-47174f00-ca91-11ea-969e-4b505488be45.png)

**Comment by mircokroon** [comment]
Isn't this already a feature? You can right-click on the map to load all existing chunks, which would draw them on the map. You can zoom on the overview by scrolling then to see more of the world.

**Comment by mircokroon** [comment]
I'm not sure how well this would work in practice, but it's definitely an interesting idea. I'll play around with it and see what can be done.

**Comment by gaming32** [comment]
bump (So many people have had this idea but it doesn’t seem to ever got much support and I’m shocked)

**Comment by mircokroon** [comment]
Yes I am aware, I have spent some time working on this already. Unfortunately it is quite a complicated problem so it'll take a at least some time longer before it's going to be completed (especially on all versions). 

Here's a small progress update, sending a single chunk that was previously downloaded:
 
https://user-images.githubusercontent.com/23699979/106533121-d649f880-64f1-11eb-8cd8-c7d7d1cbb226.mp4

**Comment by gaming32** [comment]
This is great work! Please continue the good work :+1:

**Comment by mircokroon** [comment]
Now pretty much done in #103, overall it works pretty well.

It turns out that in 1.12 and 1.13 the server doesn't actually tell us what the render distance is, so it's a bit of guesswork there which chunks we need to send to the client. For later versions this is much easier.

**Comment by mircokroon** [comment]
Now implemented in the [latest](https://github.com/mircokroon/minecraft-world-downloader/releases/latest) release

**Comment by ViVaWalze** [comment]
Hey, what about Minecraft 1.18?
Are you working on a update?
