### ISSUE TITLE
World Downloader (.exe) will not open

### ISSUE THREAD

**Issue by zwia** [mircokroon/minecraft-world-downloader#471]
When trying to open a world downloader file, the file does not open.
Windows 10
Lastest version (of wd, I also tried other versions but none of them work) for minecraft 1.17.1

**Comment by zwia** [comment]
can anyone help me?

**Comment by DenisJCZ** [comment]
yeah I have same problem

**Comment by BSBMteam** [comment]
Actually, it started working after setting up 1.19.2 on Forge!  Authenticate your session with the instructions that tell you how to do it with PowerShell, this tutorial should be accessible from the app itself
