### ISSUE TITLE
start button missing

### ISSUE THREAD

**Issue by tas367** [mircokroon/minecraft-world-downloader#477]
**Describe the bug**
Short description of what the bug is.
os: arch linux
java version:17.0.5
when launching jar the "start" button is missing

**Steps to reproduce**
If possible, describe how the bug can be achieved.

**Screenshots**

![2023-01-17_20-55](https://user-images.githubusercontent.com/97321139/213079788-72cdec94-1dd4-41eb-b7e6-22bb0c230dfd.png)

**Version**
 - Game: Minecraft 1.19.2
 - Downloader: latest
 - Launcher (if login issues): 14.2

**Comment by tas367** [comment]
If anybody else is having this issue the windows version works under wine

**Comment by Mollomm1** [comment]
i have the same problem, i am using fedora 38 (kde spin)
![image](https://github.com/mircokroon/minecraft-world-downloader/assets/68751598/5c35890f-33de-4d3f-b171-18af5c39566c)

**Comment by tas367** [comment]
Fixed at some point
