### ISSUE TITLE
Supports 1.19.2 but does not support 1.19.3.

### ISSUE THREAD

**Issue by Herman999999999** [mircokroon/minecraft-world-downloader#485]
**Describe the bug**
A lot of servers that run on 1.19.3 don't work with this tool. 

**Steps to reproduce**
Log into a 1.19.3 server on localhost.

**Log output**
```
Various log outputs, mostly relating to out-of-bound exceptions.  
...

```

**Version**
 - Game: Minecraft 1.19.3
 - Downloader: latest

Is there any ETA for 1.19.3 support? I ran Mexator's build locally on my machine and it gave similar errors.

**Comment by mircokroon** [comment]
1.19.3 is supported now on the latest version
