### ISSUE TITLE
JNI Error cannot even launch the exe :(

### ISSUE THREAD

**Issue by ChrisH811** [mircokroon/minecraft-world-downloader#486]
**Describe the bug**
literally cannot launch the app even :/
```
**Screenshots**
[If applicable, add screenshots to help explain your problem.]
https://gyazo.com/b7305621d60e851d95e371064a79d82d
https://gyazo.com/3904d650cd214a1c33bab99df61ae437

**Version**
  Windows 10
 - Game: Minecraft 1.19.2
 - Downloader: latest

**Comment by rautamiekka** [comment]
`latest` is a version number that doesn't exist.

**Comment by 7wOv6ySCjo** [comment]
> `latest` is a version number that doesn't exist.

Yes, is here, look out: https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.16.5

**Comment by ChrisH811** [comment]
> `latest` is a version number that doesn't exist.

"Cannot even launch the exe" seems pretty independent from mc version tho too

**Comment by 7wOv6ySCjo** [comment]
i have the same problem, i double click the .exe file and don't open anything... the .jar file don't have that bug. just said

**Comment by ChrisH811** [comment]
> ![properties](https://user-images.githubusercontent.com/22108822/223008920-a0fdcaa4-1eee-41e3-bc8a-db9fdb597e22.PNG)
> 
> How is it you have a GitHub account and don't know enough to allow the file on Windows ? Check the box and allow it .

Aye, listen here you smartass, nowhere on the fucking tutorial I found for this shit told me to activate the fucking file. I'd rather you have just not replied at all if you're gonna be a cocksucker. Lick my fat fucking balls.

**Comment by mircokroon** [comment]
Have a look at the [FAQ ](https://github.com/mircokroon/minecraft-world-downloader/wiki/FAQ)page.

Please try to keep it civil
