### ISSUE TITLE
Cannot connect to [server]. The server may be down or on a different address.

### ISSUE THREAD

**Issue by mygizli04** [mircokroon/minecraft-world-downloader#50]
No matter what server i try to connect to, i get the error `Cannot connect to localhost:25566. The server may be down or on a different address.`. This is not a DNS issue or anything, since even when i try localhost, it doesn't work. ( Also doesn't work on external servers, obviously. ). Minecraft just gets stuck on "Connecting to server" and there's no change at all in the server logs. This is on minecraft 1.16.1 by the way.

**Comment by mircokroon** [comment]
I think your address or port is most likely not correct. Which specific external servers have you tried?

**Comment by mygizli04** [comment]
Oh when no answer came i completely forgot about this issue, but i've managed to connect to external servers using their numerical ip instead of the actual ip.
