### ISSUE TITLE
.exe won't open on windows

### ISSUE THREAD

**Issue by seb303** [mircokroon/minecraft-world-downloader#500]
When the .exe is run, it instantly stops.  I'm on Windows 10 Pro.

It used to work, but the newer versions (tried the 3 latest releases) all quit as soon as they are run, with no log or error message that I can see.

The Java version works fine.

Is the .exe looking for the JRE in a particular place?  Maybe I have the wrong Java version there?

**Comment by Petrosado** [comment]
I have the same issue, the exe just doesn't turn on.
