### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by crbuch** [mircokroon/minecraft-world-downloader#51]
Every time I try to run it it says "A JNI error has occurred, please check your installation and try again" even though I have the latest version of java and tried reinstalling it.

**Comment by TomerGamerTV** [comment]
yes im getting it too

**Comment by Tragafantas** [comment]
Do you have JDK installed?

**Comment by Tragafantas** [comment]
Do you have Java 9 JDK Development Kit installed? You need it, it doesn't work with JRE

**Comment by mircokroon** [comment]
See #29. Run `java -version` and ensure it's at least version 1.9.
