### ISSUE TITLE
Doesn't Launch

### ISSUE THREAD

**Issue by deletdGit** [mircokroon/minecraft-world-downloader#512]
When I try to launch the .exe file it doesn't open and says it has an error.
![image](https://user-images.githubusercontent.com/130600645/231559747-60ac2c4a-4718-474f-bb1c-84ab7fba2245.png)
When I click OK it says
![image](https://user-images.githubusercontent.com/130600645/231559885-51c7c19e-6626-4abc-8d62-9c6cbccbbd37.png)
then I click OK again and it closes.

I have the latest release (v1.17.2), OS is Windows 10 Home

**Comment by deletdGit** [comment]
Also, the latest release of Java forgot to add that

**Comment by mircokroon** [comment]
you may have multiple versions installed, have a look at the [FAQ](https://github.com/mircokroon/minecraft-world-downloader/wiki/FAQ)

**Comment by deletdGit** [comment]
I don't have multiple versions, and I don't know how to check %JAVA_HOME% and %PATH% sorry

**Comment by deletdGit** [comment]
I am reinstalling Java 17 right now, then I will try it again

**Comment by deletdGit** [comment]
Still says the same thing, 20 does not work either.

**Comment by deletdGit** [comment]
Found out how to check %JAVA_HOME% and %PATH% and set those, now it just says  A Java Exception has occurred.

**Comment by mircokroon** [comment]
You can try running `java -version` on the commandline to check if its the correct version

**Comment by deletdGit** [comment]
![image](https://user-images.githubusercontent.com/130600645/231617265-6f92ac45-2cc3-4c75-83f7-46d669d1e131.png)
Sorry for even more wait, my supper was good

**Comment by deletdGit** [comment]
Why would the .exe not work but the .jar would? I double clicked the .jar like with the .exe...

**Comment by deletdGit** [comment]
Well I'm stupid and don't understand this :D
