### ISSUE TITLE
Using the 1.19.3 game version, the commands in command blocks cannot be downloaded

### ISSUE THREAD

**Issue by HAPPY157** [mircokroon/minecraft-world-downloader#530]
Using the 1.19.3 game version, the commands in command blocks
cannot be downloaded

**Comment by Tsoccerguy3** [comment]
The information in command blocks are not sent to the client , unless you have permission to click and open and edit a command block on a server. This would be the same as chests and any other block that has NBT data stored with it . This is not a bug ! . To get that data you need server perms to edit the block. You should close this issue
