### ISSUE TITLE
Realm still says "connect to localhost to start"

### ISSUE THREAD

**Issue by miinstrel** [mircokroon/minecraft-world-downloader#537]
Steps to recreate:
1. Launch MC vanilla 1.20
2. Connect to Realm
3. Open World Downloader
4. Go to 'Realms' tab, enter username, Load, Request IP, and Select (which populates IP/port into the 'Connection' tab
5. Click Start

Map remains blank with white player icon in the middle and "Connect to address localhost:25565 to start downloading" message at the top.
Same thing happens if I manually enter the server ip / port.

**Comment by mircokroon** [comment]
Are you connecting directly to the realm in Minecraft? You need to go to the regular multiplayer tab and connect to the `localhost:25565` server in-game instead of through realms.
