### ISSUE TITLE
Error: A JNI error has occurred, please check your installation and try again

### ISSUE THREAD

**Issue by realKeehan** [mircokroon/minecraft-world-downloader#539]
**Describe the bug**
Application crashes and doesnt connect to server

**Steps to reproduce**
Try to connect to a server

**Log output**
```
Error: A JNI error has occurred, please check your installation and try again

A java exception has occured  
...

```
**Version**
 - Game: Minecraft 1.19.1
 - Downloader: latest
 - Launcher (if login issues): 14.2

**Comment by mircokroon** [comment]
Check the [FAQ](https://github.com/mircokroon/minecraft-world-downloader/wiki/FAQ)
