### ISSUE TITLE
Having Trouble with World Downloader

### ISSUE THREAD

**Issue by AlexisRose733** [mircokroon/minecraft-world-downloader#541]
I'm just having problems with this app in general. I attempted to use it on a server, but in the instructions, it says to connect to localhost:25565 and I can't figure out why it doesn't work. There's an error message on the "server" and won't let me connect, which means the downloader doesn't work. Am I just doing it wrong or are there missing instruction steps?
![2023-06-13_05 40 49](https://github.com/mircokroon/minecraft-world-downloader/assets/113883567/614bd6ea-1f06-47b6-8797-043d5e59492b)

**Comment by mircokroon** [comment]
Use the issue template
