### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by X3M0Nn** [mircokroon/minecraft-world-downloader#547]
**Describe the bug**
It's can't be opem

**Steps to reproduce**
I can't open it because it show i don't have java 17 but i have this

**Log output**
```
...

```
**Screenshots**
![image](https://github.com/mircokroon/minecraft-world-downloader/assets/135415899/2571b8f2-0d62-4aa1-85f9-5c6ba322305d)
![image](https://github.com/mircokroon/minecraft-world-downloader/assets/135415899/42345d9a-a957-4023-810a-e62e3c644278)

**Version**
 - Game: Minecraft 1.19.2
 - Downloader: latest

**Comment by Microtized** [comment]
Same issue, haven't found a solution just yet

**Comment by Microtized** [comment]
download JRE 17 from here:
https://www.oracle.com/java/technologies/javase/jdk17-archive-downloads.html

**Comment by mircokroon** [comment]
Yup, check the [FAQ](https://github.com/mircokroon/minecraft-world-downloader/wiki/FAQ)
