### ISSUE TITLE
Program refuses to run

### ISSUE THREAD

**Issue by KingBlueBrine** [mircokroon/minecraft-world-downloader#567]
When running the .exe file it says that I don't have Java Runtime Environment 17 when I have the latest version of Java, I even downloaded the Java file on the page it sends you to.

I have gotten the same result on another Windows 10 device with same Java.

**Comment by michelle1574** [comment]
You need to download actually this kind of Java:
https://www.oracle.com/java/technologies/downloads/#jdk17-windows
