### ISSUE TITLE
Option to force connect even if server is down

### ISSUE THREAD

**Issue by nachog2003** [mircokroon/minecraft-world-downloader#57]
I'm trying to download a few chunks off a world hosted on Minecraft Realms, but Realms have a weird thing where if you get the IP the server is running on and add it to your Multiplayer menu, it'll come up with a "Can't connect to server" error, but if you double click it and connect anyway it'll work just fine, thing is I assume the program makes it so that if it detects it's down it just won't even try to connect. Is there any way to make it connect even if it gets that error?

**Comment by mircokroon** [comment]
Hmm there shouldn't be anything to prevent it from trying to connect. What is the current results? Does it print anything in the terminal? 

I unfortunately don't have access to a realm to try this on so it's a bit hard to fix.

**Comment by 8bit-coder** [comment]
I've actually downloaded realm worlds before, and it should work perfectly fine(in my case it was 1.16.1). As long as the realm hasn't changed IPs, you should be fine using the downloader.
