### ISSUE TITLE
Program is not running

### ISSUE THREAD

**Issue by Abigail7200** [mircokroon/minecraft-world-downloader#572]
Program is not running even in admin mode. I've tried to run the .exe and the .jar

**Comment by rautamiekka** [comment]
Logs would be useful.

**Comment by Abigail7200** [comment]
Hello, I do not have any logs. I try to run the .exe I've downloaded and nothing happens, simple as that. Where would logs be saved?

**Comment by CUBICinfinity** [comment]
I have the same problem. It might be related to Windows security. But I also don't know where logs would be saved.
