### ISSUE TITLE
Do I have to load chunks for them to be downloaded?

### ISSUE THREAD

**Issue by js802025** [mircokroon/minecraft-world-downloader#58]
How do I go about downloading my world I’m connected to local host, if I do need to move around is there a feature that tps me to where I need to go?

**Comment by js802025** [comment]
My console also keeps printing this:
`java.lang.RuntimeException: VarInt lacks bytes! We may be out of sync now.
	at packets.DataReader.readVarInt(DataReader.java:68)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:100)
	at game.data.chunk.palette.Palette.readPalette(Palette.java:69)
	at game.data.chunk.Chunk.readChunkColumn(Chunk.java:131)
	at game.data.chunk.Chunk.parse(Chunk.java:269)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:204)
	at game.data.chunk.ChunkFactory.run(ChunkFactory.java:154)
Chunk could not be parsed!`

**Comment by mircokroon** [comment]
If it's a local server, why do you need to download it? Teleporting the player around is not really within the scope of this application.

What version is this?

**Comment by js802025** [comment]
It's not, the directions say to connect to localhost. I was thinking teleporting around would load chunks... I'm in version 1.16.1

**Comment by mircokroon** [comment]
Ah, I misunderstood then. Well you need to load the chunks for them to be downloaded, e.g. by walking around. You could use a different solution (client mod, scripts, command blocks, etc) to teleport if you want to automate it.

**Comment by MasterPencil** [comment]
Hi I tried using this but where do the world downloads go? What is "world/"?

**Comment by js802025** [comment]
world/ would be the overworld.

**Comment by mircokroon** [comment]
I think this has been resolved
