### ISSUE TITLE
Doesn't launch

### ISSUE THREAD

**Issue by An1me2b2t** [mircokroon/minecraft-world-downloader#584]
I click on the .exe and nothing happens. I try to run the Jar and nothing happens. Not sure where any kind of logs for that would be stored.

**Comment by An1me2b2t** [comment]
.exe doesn't work but I did get the .jar to launch by uninstalling java completely and installing the most recent JRE. Hope this helps someone

**Comment by gabessdsp** [comment]
I am experiencing the same issue with the exe and would prefer to use that. Hopefully this gets some attention
