### ISSUE TITLE
Is there any way to block this plugin on a server?

### ISSUE THREAD

**Issue by matipoirierg** [mircokroon/minecraft-world-downloader#585]
Hi, so I work selling custom minecraft maps and I showcase them on a server. I'm having trouble because people are leaking my worlds using this client, any way to prevent this?

**Comment by mircokroon** [comment]
Unfortunately there is no way to do that, sorry about that

**Comment by rautamiekka** [comment]
I remember one downloader would check if the Server had a Server-side counterpart addon. If it did, the downloader would only do what the Server addon allowed, otherwise it would work like everything was allowed.

**Comment by mircokroon** [comment]
Yup, there's an old discussion on that here: https://github.com/mircokroon/minecraft-world-downloader/issues/63

I'll close this since it's a duplicate
