### ISSUE TITLE
All dimensions' chunks are being written to the overworld (1.16.2)

### ISSUE THREAD

**Issue by Malsententia** [mircokroon/minecraft-world-downloader#64]
Thanks for getting updating it for 1.16.2! However, there seems to be a bug with how other dimensions' chunks are being saved; everything's ending up in the overworld. Server is mostly vanilla, tested with a vanilla client as well.
Let me know if you CNR and I can get more info if needed. Thanks!
![bug](https://user-images.githubusercontent.com/1284257/91381596-a11bda80-e7dc-11ea-8ba5-ac66d0c975c4.png)

**Comment by Tragafantas** [comment]
Try downloading the nether on another world file, then merging the nether by changing the file name and replacing

**Comment by Malsententia** [comment]
Yeah, that's what I ended up doing, though it's problematic because of course I have to stop and start the program any time I want to go through a portal.
