### ISSUE TITLE
Is it possible to detect mircokroon's world downloader?

### ISSUE THREAD

**Issue by Aydieton** [mircokroon/minecraft-world-downloader#664]
Is it possible to detect mircokroon's world downloader from server?
@mircokroon or anyone

**Comment by mircokroon** [comment]
No.

**Comment by rautamiekka** [comment]
An anticheat might detect from the pattern of downloading, but that's a cat-and-mouse game.

**Comment by Aydieton** [comment]
> An anticheat might detect from the pattern of downloading, but that's a cat-and-mouse game.

wdym so they can detect or not?

**Comment by Aydieton** [comment]
> No.

so they cannot detect or make log about this world downloader?

**Comment by Aydieton** [comment]
> > No.
> 
> so they cannot detect or make log about this world downloader?
