### ISSUE TITLE
How to remove world generation?

### ISSUE THREAD

**Issue by GosbKom** [mircokroon/minecraft-world-downloader#666]
I download the bedwars arena, the whole world is empty, there is only the ARENA itself, but when I downloaded the world and go to it, there is NO emptiness around, the usual minecraft world is generated, is this fixable?

**Comment by Ikethepro18** [comment]
In the "World" tab you can select "Prevent Chunk Generation"
![image](https://github.com/mircokroon/minecraft-world-downloader/assets/73065710/43bfc07a-15fc-4383-8895-6a8d1c031b49)
