### ISSUE TITLE
Failed to decode packet 'clientbound:/minecraft:hello'

### ISSUE THREAD

**Issue by Plackett** [mircokroon/minecraft-world-downloader#669]
**Describe the bug**
Can not use world downloader on a 1.20.5 server, fails to connect with a DecodeException from io.netty.handler.codec.

**Steps to reproduce**
Run world downloader on a 1.20.5 server and try to connect to localhost:25565,
then you will receive the error I'm having.

**Log output**
```
Not Applicable

```
**Screenshots**
![Screenshot 2024-05-16 113930](https://github.com/mircokroon/minecraft-world-downloader/assets/80919085/70cc481f-5e5b-436b-9cb3-db75a6acf8a1)

**Version**
 - Game: Minecraft 1.20.5
 - Downloader: latest

**Comment by AskSkivdal** [comment]
Im having the same problem when connecting from 1.20.6. Connecting to the server works without issues on vanilla and fabric when connecting directly to the target server.

Here is the full log output from world-downloader with --dev-mode on.

```
mai 17, 2024 10:07:04 A.M. com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @2d6a9952'
Starting proxy for play.nordvilla.eu. Make sure to connect to localhost:10000 instead of the regular server address.
Performed handshake with {CENSORED}:25565, protocol version 766
Server probably disconnected. Waiting for new connection...
Performed handshake with {CENSORED}:25565, protocol version 766
Login by: {CENSORED}
Client probably disconnected. Waiting for new connection...
Performed handshake with {CENSORED}:25565, protocol version 766
Login by: {CENSORED}
Client probably disconnected. Waiting for new connection...
```

**Comment by Dam-Buty** [comment]
Same issue on 1.20.6

**Comment by Alphaotic** [comment]
java -jar world-downloader.jar --dev-mode
May 27, 2024 12:25:25 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @22a71081'
Starting proxy for mc.hypixel.net. Make sure to connect to localhost:25565 instead of the regular server address.
Performed handshake with mc.hypixel.net:25565, protocol version 766
Login by: xxxxxxxx
Client probably disconnected. Waiting for new connection...

i'm seeing the same issue on 1.20.6, was trying to import hypixel smp world data

**Comment by memesdraws** [comment]
was this ever looked into/resolved? trying to download 1.20.6 worlds on hypixel as well

**Comment by lucastwg** [comment]
+1, happening on 1.20.6

**Comment by imcynic** [comment]
+1, happening on 1.20.6

**Comment by ZenaAccel** [comment]
i am also having this issue, hopefully this is fixed soon?

**Comment by calmsacibis995** [comment]
Same issue on 1.21.

**Comment by Lavshyak** [comment]
try to change your nickname to more shorter. it works for my friend.

**Comment by zs-yg** [comment]
+1,1.21.1

**Comment by amrilll0007-ship-it** [comment]
Terjadi bug pada 1.21.6 bang

**Comment by SonarDesdelauna** [comment]
same prob on 1.21.11
