### ISSUE TITLE
World not downloading

### ISSUE THREAD

**Issue by LightslicerGP** [mircokroon/minecraft-world-downloader#676]
**Describe the bug**
I join localhost, and it does not load

**Steps to reproduce**
1. launch world downloader
2. put in ip
3. start
4. open localhost on mc

**Screenshots**

https://github.com/mircokroon/minecraft-world-downloader/assets/63020072/6804d007-a033-4cec-b1d9-e5e976343710

**Version**
 - Game: Minecraft 1.21
 - Downloader: latest

**Comment by LightslicerGP** [comment]
Update: even after closing the program, deleting all the folders it created, and relaunching, i joined the server and its been on this screen for a long time now, and hasn't updated
![image](https://github.com/mircokroon/minecraft-world-downloader/assets/63020072/50c85b8a-4701-45e6-9484-71f9539c0748)

**Comment by mircokroon** [comment]
That's strange, could you try running through the commandline with `java -jar world-downloader.jar --dev-mode`?

**Comment by LightslicerGP** [comment]
![image](https://github.com/mircokroon/minecraft-world-downloader/assets/63020072/bbcf3c2e-f146-44c7-ace5-de80f363002b)

**Comment by mircokroon** [comment]
I think most likely the server is using custom dimensions which isn't being handled well by the downloader currently, will try to fix that

**Comment by mircokroon** [comment]
Hopefully fixed in this [pre-release](https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.18.1a)
