### ISSUE TITLE
Any way to download a realm world?

### ISSUE THREAD

**Issue by Klish132** [mircokroon/minecraft-world-downloader#7]
My friend (who is the owner) lost access to his MC account, so we're trying to download the realm world. I found the realm IP and port, but world downloader keeps saying "Cannot connect to <adress>. The server may be down or on a different address." and I can't connect to locahost.

**Comment by Klish132** [comment]
EDIT: Turns out I just needed to do --server <ip> --port <port> instead of putting both ip and port after --server. Just had to think a bit :D. Very good tool!

**Comment by 8bit-coder** [comment]
Hey, I'm also trying to download a realm. How did you get the realm IP and port? Googling doesn't help.

**Comment by ChillerDragon** [comment]
@8bit-coder I have no clue about realms but if you can connect to it you can use wireshark to see ip and port.
