### ISSUE TITLE
I'm Really confused how to use this, please help

### ISSUE THREAD

**Issue by SwiftPicard** [mircokroon/minecraft-world-downloader#73]

**Comment by mircokroon** [comment]
The instructions in the readme cover most of it:

> Download the latest release and execute the jar file using the commandline by running:
> ```java -jar world-downloader.jar -s address.to.server.com```
> Then connect to `localhost` in Minecraft to start downloading the world. The world will be saved to the world/ by default.

So after downloading the .jar file you will need to open a command prompt / terminal and run the given command shown there.
