### ISSUE TITLE
Cannot connect to 2b2t.org

### ISSUE THREAD

**Issue by ChillerDragon** [mircokroon/minecraft-world-downloader#74]
I used the world downloader just fine for a few days on 2b2t.org but after one reconnect it broke.
When I fetch the serverinfo from localhost I keep getting:

```
Cannot connect to 2b2t.org. The server may be down or on a different address.
```

Did I mess something up? Is it a bug in the tool? Did the server change something? Could one please try to reproduce.

**Comment by mircokroon** [comment]
I've tested it on this server without issues before. Is it still happening now or was it a temporary thing?

**Comment by ChillerDragon** [comment]
Yea the issue seems to be permanent. Well at least across reboots and for multiple days. Only tested on one machine. And compared against one other server that still works.

I will do further tests with different devices/accounts/servers in the next few days maybe.

It is probably not a bug or limitation of the downloader. Since it broke without updating the tool. I initially thought maybe something on the server side changed because other servers still work. But I also seem to be the only person who currently has issues to get [2bored2wait proxy](https://github.com/themoonisacheese/2bored2wait) connected. Maybe something on my side broke. This issue is more a cry for help than a bug report on this specific tool, sorry. If you have no idea on how to fix or investigate further feel free to close this issue.

**Comment by mircokroon** [comment]
I could reproduce it exactly once, and now not anymore... I would guess it's something to do with the server?

**Comment by mircokroon** [comment]
Actually, that's because I accidentally fixed the issue. It looks like 2b2t has an SRV record now, leading to ```connect.2b2t.org```.

**Comment by ChillerDragon** [comment]
Nice thanks! I can confirm its now working on my side :+1:
