### ISSUE TITLE
Doesnt save chest/modified data?

### ISSUE THREAD

**Issue by daiiwulf** [mircokroon/minecraft-world-downloader#75]
After a little wrangling with java (needed JDK13 as it would not run with runtime JRE8) I got the jar to run, and connect to a server (mc 1.12.2, vanilla), and proxy a client just fine. It appeared to be working. I opened a few chests to get their inventory, disconnected from the server, then copied the saved world data from the output directory I had specified to a new sp map, started the game on that sp map.. and nothing? The terrain was present as expected, but the chest I had put down and filled with test inventory was not present.

I tried a second time, and this time the chest was saved, but none of its contents?

I'm using the latest available jar from the download link. Is there something I'm missing here?

**Comment by mircokroon** [comment]
Currently saving chests doesn't work yet on version 1.12, only on 1.13+.

**Comment by daiiwulf** [comment]
Ahh, that would do it. 

I've now tested on 1.13.2 and ran into another issue, will close this and pop open a new issue as that is something different.  Thanks!
