### ISSUE TITLE
Nether chunks are written to region/

### ISSUE THREAD

**Issue by ChillerDragon** [mircokroon/minecraft-world-downloader#78]
I guess since d350b5384f8456ec516b75dffe68edb027b23666 the directorys DIM1 and DIM-1 are created and should be used. Seems like for me I get all files from overworld and nether into region/. Tested in 1.12.2 (2b2t.org) with downloader version 4acb71bd2ba692986151ba260ed13754d7238ae6.

**Comment by mircokroon** [comment]
Looks like I might have expertly implemented the dimension handling only for 1.16, should be a straightforward fix
