### ISSUE TITLE
Dimensions overlapping

### ISSUE THREAD

**Issue by 8bitFra** [mircokroon/minecraft-world-downloader#83]
When I enter a dimension like the end the corresponding chunks generated in the overworld are overwritten by the new dimension! (version 1.16.1)

**Comment by mircokroon** [comment]
I can't reproduce this, are you using the latest version of the downloader?

**Comment by 8bitFra** [comment]
Yes, of course. Maybe I'll try again tomorrow and let you know!

**Comment by 8bitFra** [comment]
Sorry for the delay but I completely forgot to try again! I did a test with the latest version of world-downloader (1.8.1) and minecraft 1.16.4 and this time it worked. I don't know why on that server in 1.16.1 it didn't work properly ... Unfortunately I can't double check in the same conditions because the mentioned server is closed, so I consider this problem as solved! Thanks.
