### ISSUE TITLE
Feature request: Custom Dimension support.

### ISSUE THREAD

**Issue by JasonTable** [mircokroon/minecraft-world-downloader#92]
Most servers run modded software that enables them to have custom dimensions in addition to the main 3. I have been playing around with my own minecraft servers and i noticed that in 1.16.4, the client knows if it is in a custom dimension.

Here is what I mean. Let's say I start up a papermc minecraft server with the multiverse plugin installed and i create some dimensions such as one named "test". Now in the F3 debug menu on line 8, there is a line that tells you what dimension you are in. Normally it would say something like "minecraft:overworld" or "minecraft:the_end" but since minecraft 1.16, if i am on a dimension created with multiverse or some other world manager plugin, i will see "minecraft:[world name]" in line 8 of the f3 menu. so if i am in the dimension named "test" i will see "minecraft:test".

So what i am trying to say is that since the minecraft client now knows if it is a custom dimension, i think that this proxy could take advantage of that to save multiple dimensions into different world folders. Or it could save them as custom dimensions in the offline world since minecraft 1.16 supports custom dimensions in single player worlds. Or it could be used to filter what chunks are saved so as to prevent a bug that is caused due to a lack of dimension support. By "filter" i mean maybe there can be a setting to only save a certain dimension for example, the "minecraft:test" custom dimension. so if i am in the "minecraft:overworld" dimension, it will not save chunks but when i enter the test dimension, it will start saving chunks and when i leave the test dimension it will stop.

I guess this is kind of both a bug report and feature request because I believe that if this feature were implemented, it would fix the bug i am about to explain.

The bug is that if i am in one custom dimension and saving chunks there, then I go to a different custom dimension, the chunks in the new dimension will start overwriting the chunks from the old one. Here is a picture of what that looks like:

![2020-12-14_17 36 54](https://user-images.githubusercontent.com/69403976/102144227-1b777580-3e33-11eb-939c-455c949db610.png)

The grass chunks are the old dimension and the water chunks are from the new one.

The version of minecraft-world-downloader I am using is v1.8.3

**Comment by mircokroon** [comment]
This should definitely be supported, will have to figure out how the dimensions are stored in singleplayer I suppose

**Comment by mircokroon** [comment]
This should now be supported in the latest version
