### ISSUE TITLE
java.lang.RuntimeException: Client not authenticated!

### ISSUE THREAD

**Issue by ElwoodHogan** [mircokroon/minecraft-world-downloader#93]
Im trying to connect to a server through localhost, and when i attempt to, the console gives me this error:
https://pastebin.com/XmVKwfy0

**Comment by mircokroon** [comment]
Try restarting the downloader after having started Minecraft

**Comment by ElwoodHogan** [comment]
> Try restarting the downloader after having started Minecraft

I ran the command : java -jar C:\Users\leonh\Downloads\world-downloader.jar -s interactions.mym.li
only once i had gotten to the server menu and I still got the same error when trying to connect.
However, usually the server would just say "Disconnected".  Now it is giving me this error:
"io.netty.channel.abstractchannel$annotatedconnectexception: connection refused: no further information"

**Comment by mircokroon** [comment]
Which launcher version are you using?

**Comment by ElwoodHogan** [comment]
> Which launcher version are you using?

I am on minecraft 1.12.2 using the FTB Launcher running Interactions 2.0.9

**Comment by mircokroon** [comment]
This is probably fixed now (hopefully), if not feel free to let me know and I'll investigate more
