### ISSUE TITLE
Multi World support

### ISSUE THREAD

**Issue by ZaptoInc** [mircokroon/minecraft-world-downloader#94]
Hello, i would like to download a specific map from a server, but then going in the nether, it replaces the overworld with the nether, is there a way to support multi-world?

**Comment by DillFrescott** [comment]
I was just about to ask this same question after testing it.

**Comment by DillFrescott** [comment]
It needs multi world to work properly on servers IMO

**Comment by mircokroon** [comment]
At least dimensions should already be supported, this could just be related to #92

**Comment by mircokroon** [comment]
Should now be fixed.
