### ISSUE TITLE
Error when drawing chunks before connecting to server.

### ISSUE THREAD

**Issue by Esper89** [mircokroon/minecraft-world-downloader#95]
Upon clicking "Draw all existing chunks" before the client connects, the existing chunks are not drawn and [quite a lot of text](https://github.com/mircokroon/minecraft-world-downloader/files/5755978/stderr.txt) is sent to stderr. It's the same text every time.

**Comment by mircokroon** [comment]
Yeah this is known, it just doesn't know how to load in the chunks without a Minecraft version being picked. The option should just be disabled.

**Comment by mircokroon** [comment]
Actually ended up just making it work instead of disabling the option
