### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by Jacob345k** [mircokroon/minecraft-world-downloader#97]
https://i.imgur.com/o0WAkBD.png
Disconnected instantly on join, but was working before. No noticeable changes since working, 1.16.4, vanilla client. Probably just me doing something stupid idk

**Comment by mircokroon** [comment]
This could be related to the launcher version, restarting the game and downloader may resolve it. This should be a bit more robust in (upcoming) version 1.8.4 I hope.
